GNU Radio's DSD Package: testing::internal::linked_ptr< T > Class Template Reference
testing::internal::linked_ptr< T > Class Template Reference
#include <gtest-linked_ptr.h>
Public Types
typedef T element_type
typedef T element_type
Public Member Functions
linked_ptr (T *ptr=NULL)
~linked_ptr ()
template<typename U >
linked_ptr (linked_ptr< U > const &ptr)
linked_ptr (linked_ptr const &ptr)
template<typename U >
linked_ptr & operator= (linked_ptr< U > const &ptr)
linked_ptr & operator= (linked_ptr const &ptr)
void reset (T *ptr=NULL)
T * get () const
T * operator-> () const
T & operator* () const
bool operator== (T *p) const
bool operator!= (T *p) const
template<typename U >
bool operator== (linked_ptr< U > const &ptr) const
template<typename U >
bool operator!= (linked_ptr< U > const &ptr) const
linked_ptr (T *ptr=NULL)
~linked_ptr ()
template<typename U >
linked_ptr (linked_ptr< U > const &ptr)
linked_ptr (linked_ptr const &ptr)
template<typename U >
linked_ptr & operator= (linked_ptr< U > const &ptr)
linked_ptr & operator= (linked_ptr const &ptr)
void reset (T *ptr=NULL)
T * get () const
T * operator-> () const
T & operator* () const
bool operator== (T *p) const
bool operator!= (T *p) const
template<typename U >
bool operator== (linked_ptr< U > const &ptr) const
template<typename U >
bool operator!= (linked_ptr< U > const &ptr) const
Friends
template<typename U >
class linked_ptr
template<typename U >
class linked_ptr
Member Typedef Documentation
element_type [1/2]
template<typename T > typedef T testing::internal::linked_ptr< T >::element_type
element_type [2/2]
template<typename T > typedef T testing::internal::linked_ptr< T >::element_type
Constructor & Destructor Documentation
linked_ptr() [1/6]
template<typename T > testing::internal::linked_ptr< T >::linked_ptr (T * ptr = NULL) inline explicit
~linked_ptr() [1/2]
template<typename T > testing::internal::linked_ptr< T >::~linked_ptr () inline
linked_ptr() [2/6]
template<typename T > template<typename U > testing::internal::linked_ptr< T >::linked_ptr (linked_ptr< U > const & ptr) inline
linked_ptr() [3/6]
template<typename T > testing::internal::linked_ptr< T >::linked_ptr (linked_ptr< T > const & ptr) inline
linked_ptr() [4/6]
template<typename T > testing::internal::linked_ptr< T >::linked_ptr (T * ptr = NULL) inline explicit
~linked_ptr() [2/2]
template<typename T > testing::internal::linked_ptr< T >::~linked_ptr () inline
linked_ptr() [5/6]
template<typename T > template<typename U > testing::internal::linked_ptr< T >::linked_ptr (linked_ptr< U > const & ptr) inline
linked_ptr() [6/6]
template<typename T > testing::internal::linked_ptr< T >::linked_ptr (linked_ptr< T > const & ptr) inline
Member Function Documentation
get() [1/2]
template<typename T > T * testing::internal::linked_ptr< T >::get () const inline
Referenced by testing::internal::linked_ptr< T >::operator!=(), testing::internal::operator!=(), testing::internal::linked_ptr< T >::operator==(), and testing::internal::operator==().
get() [2/2]
template<typename T > T * testing::internal::linked_ptr< T >::get () const inline
operator!=() [1/4]
template<typename T > template<typename U > bool testing::internal::linked_ptr< T >::operator!= (linked_ptr< U > const & ptr) const inline
References testing::internal::linked_ptr< T >::get().
operator!=() [2/4]
template<typename T > template<typename U > bool testing::internal::linked_ptr< T >::operator!= (linked_ptr< U > const & ptr) const inline
operator!=() [3/4]
template<typename T > bool testing::internal::linked_ptr< T >::operator!= (T * p) const inline
operator!=() [4/4]
template<typename T > bool testing::internal::linked_ptr< T >::operator!= (T * p) const inline
operator*() [1/2]
template<typename T > T & testing::internal::linked_ptr< T >::operator* () const inline
operator*() [2/2]
template<typename T > T & testing::internal::linked_ptr< T >::operator* () const inline
operator->() [1/2]
template<typename T > T * testing::internal::linked_ptr< T >::operator-> () const inline
operator->() [2/2]
template<typename T > T * testing::internal::linked_ptr< T >::operator-> () const inline
operator=() [1/4]
template<typename T > linked_ptr & testing::internal::linked_ptr< T >::operator= (linked_ptr< T > const & ptr) inline
operator=() [2/4]
template<typename T > linked_ptr & testing::internal::linked_ptr< T >::operator= (linked_ptr< T > const & ptr) inline
operator=() [3/4]
template<typename T > template<typename U > linked_ptr & testing::internal::linked_ptr< T >::operator= (linked_ptr< U > const & ptr) inline
operator=() [4/4]
template<typename T > template<typename U > linked_ptr & testing::internal::linked_ptr< T >::operator= (linked_ptr< U > const & ptr) inline
operator==() [1/4]
template<typename T > template<typename U > bool testing::internal::linked_ptr< T >::operator== (linked_ptr< U > const & ptr) const inline
References testing::internal::linked_ptr< T >::get().
operator==() [2/4]
template<typename T > template<typename U > bool testing::internal::linked_ptr< T >::operator== (linked_ptr< U > const & ptr) const inline
operator==() [3/4]
template<typename T > bool testing::internal::linked_ptr< T >::operator== (T * p) const inline
operator==() [4/4]
template<typename T > bool testing::internal::linked_ptr< T >::operator== (T * p) const inline
reset() [1/2]
template<typename T > void testing::internal::linked_ptr< T >::reset (T * ptr = NULL) inline
reset() [2/2]
template<typename T > void testing::internal::linked_ptr< T >::reset (T * ptr = NULL) inline
Friends And Related Symbol Documentation
linked_ptr [1/2]
template<typename T > template<typename U > friend class linked_ptr friend
linked_ptr [2/2]
template<typename T > template<typename U > class linked_ptr friend
The documentation for this class was generated from the following files:
dsd/test/gtest/include/gtest/internal/gtest-linked_ptr.h
mbelib/test/gtest/include/gtest/internal/gtest-linked_ptr.h