GNU Radio's DSD Package: testing::internal::QuantifierMatcherImpl< Container > Class Template Reference
testing::internal::QuantifierMatcherImpl< Container > Class Template Reference
#include <gmock-matchers.h>
Public Types
typedef StlContainerView< RawContainer > View
typedef View::type StlContainer
typedef View::const_reference StlContainerReference
typedef StlContainer::value_type Element
typedef StlContainerView< RawContainer > View
typedef View::type StlContainer
typedef View::const_reference StlContainerReference
typedef StlContainer::value_type Element
Public Member Functions
typedef GTEST_REMOVE_REFERENCE_AND_CONST_ (Container) RawContainer
template<typename InnerMatcher >
QuantifierMatcherImpl (InnerMatcher inner_matcher)
bool MatchAndExplainImpl (bool all_elements_should_match, Container container, MatchResultListener *listener) const
typedef GTEST_REMOVE_REFERENCE_AND_CONST_ (Container) RawContainer
template<typename InnerMatcher >
QuantifierMatcherImpl (InnerMatcher inner_matcher)
bool MatchAndExplainImpl (bool all_elements_should_match, Container container, MatchResultListener *listener) const
Public Member Functions inherited from testing::MatcherInterface< Container >
virtual bool MatchAndExplain (Container x, MatchResultListener *listener) const=0
virtual bool MatchAndExplain (Container x, MatchResultListener *listener) const=0
Public Member Functions inherited from testing::MatcherDescriberInterface
virtual ~MatcherDescriberInterface ()
virtual void DescribeTo (::std::ostream *os) const =0
virtual void DescribeNegationTo (::std::ostream *os) const
virtual ~MatcherDescriberInterface ()
virtual void DescribeTo (::std::ostream *os) const =0
virtual void DescribeNegationTo (::std::ostream *os) const
Protected Member Functions
GTEST_DISALLOW_ASSIGN_ (QuantifierMatcherImpl)
GTEST_DISALLOW_ASSIGN_ (QuantifierMatcherImpl)
Protected Attributes
const Matcher< const Element & > inner_matcher_
Member Typedef Documentation
Element [1/2]
template<typename Container > typedef StlContainer::value_type testing::internal::QuantifierMatcherImpl< Container >::Element
Element [2/2]
template<typename Container > typedef StlContainer::value_type testing::internal::QuantifierMatcherImpl< Container >::Element
StlContainer [1/2]
template<typename Container > typedef View::type testing::internal::QuantifierMatcherImpl< Container >::StlContainer
StlContainer [2/2]
template<typename Container > typedef View::type testing::internal::QuantifierMatcherImpl< Container >::StlContainer
StlContainerReference [1/2]
template<typename Container > typedef View::const_reference testing::internal::QuantifierMatcherImpl< Container >::StlContainerReference
StlContainerReference [2/2]
template<typename Container > typedef View::const_reference testing::internal::QuantifierMatcherImpl< Container >::StlContainerReference
View [1/2]
template<typename Container > typedef StlContainerView<RawContainer> testing::internal::QuantifierMatcherImpl< Container >::View
View [2/2]
template<typename Container > typedef StlContainerView<RawContainer> testing::internal::QuantifierMatcherImpl< Container >::View
Constructor & Destructor Documentation
QuantifierMatcherImpl() [1/2]
template<typename Container > template<typename InnerMatcher > testing::internal::QuantifierMatcherImpl< Container >::QuantifierMatcherImpl (InnerMatcher inner_matcher) inline explicit
QuantifierMatcherImpl() [2/2]
template<typename Container > template<typename InnerMatcher > testing::internal::QuantifierMatcherImpl< Container >::QuantifierMatcherImpl (InnerMatcher inner_matcher) inline explicit
Member Function Documentation
GTEST_DISALLOW_ASSIGN_() [1/2]
template<typename Container > testing::internal::QuantifierMatcherImpl< Container >::GTEST_DISALLOW_ASSIGN_ (QuantifierMatcherImpl< Container >) protected
GTEST_DISALLOW_ASSIGN_() [2/2]
template<typename Container > testing::internal::QuantifierMatcherImpl< Container >::GTEST_DISALLOW_ASSIGN_ (QuantifierMatcherImpl< Container >) protected
GTEST_REMOVE_REFERENCE_AND_CONST_() [1/2]
template<typename Container > typedef testing::internal::QuantifierMatcherImpl< Container >::GTEST_REMOVE_REFERENCE_AND_CONST_ (Container)
GTEST_REMOVE_REFERENCE_AND_CONST_() [2/2]
template<typename Container > typedef testing::internal::QuantifierMatcherImpl< Container >::GTEST_REMOVE_REFERENCE_AND_CONST_ (Container)
MatchAndExplainImpl() [1/2]
template<typename Container > bool testing::internal::QuantifierMatcherImpl< Container >::MatchAndExplainImpl (bool all_elements_should_match, Container container, MatchResultListener * listener) const inline
References testing::internal::StlContainerView< RawContainer >::ConstReference(), testing::internal::QuantifierMatcherImpl< Container >::inner_matcher_, testing::internal::PrintIfNotEmpty(), testing::StringMatchResultListener::str(), and testing::MatchResultListener::stream().
Referenced by testing::internal::ContainsMatcherImpl< Container >::MatchAndExplain(), and testing::internal::EachMatcherImpl< Container >::MatchAndExplain().
MatchAndExplainImpl() [2/2]
template<typename Container > bool testing::internal::QuantifierMatcherImpl< Container >::MatchAndExplainImpl (bool all_elements_should_match, Container container, MatchResultListener * listener) const inline
References testing::internal::StlContainerView< RawContainer >::ConstReference(), testing::internal::QuantifierMatcherImpl< Container >::inner_matcher_, testing::internal::PrintIfNotEmpty(), and testing::StringMatchResultListener::str().
Member Data Documentation
inner_matcher_
template<typename Container > const Matcher< const Element & > testing::internal::QuantifierMatcherImpl< Container >::inner_matcher_ protected
Referenced by testing::internal::ContainsMatcherImpl< Container >::DescribeNegationTo(), testing::internal::EachMatcherImpl< Container >::DescribeNegationTo(), testing::internal::ContainsMatcherImpl< Container >::DescribeTo(), testing::internal::EachMatcherImpl< Container >::DescribeTo(), and testing::internal::QuantifierMatcherImpl< Container >::MatchAndExplainImpl().
The documentation for this class was generated from the following files:
dsd/test/gmock/include/gmock/gmock-matchers.h
mbelib/test/gmock/include/gmock/gmock-matchers.h