GNU Radio's DSD Package: testing::DefaultValue< T & > Class Template Reference
testing::DefaultValue< T & > Class Template Reference
#include <gmock-actions.h>
Static Public Member Functions
static void Set (T &x)
static void Clear ()
static bool IsSet ()
static bool Exists ()
static T & Get ()
static void Set (T &x)
static void Clear ()
static bool IsSet ()
static bool Exists ()
static T & Get ()
Member Function Documentation
Clear() [1/2]
template<typename T > static void testing::DefaultValue< T & >::Clear () inline static
Clear() [2/2]
template<typename T > static void testing::DefaultValue< T & >::Clear () inline static
Exists() [1/2]
template<typename T > static bool testing::DefaultValue< T & >::Exists () inline static
References testing::internal::BuiltInDefaultValue< T >::Exists().
Exists() [2/2]
template<typename T > static bool testing::DefaultValue< T & >::Exists () inline static
References testing::internal::BuiltInDefaultValue< T >::Exists().
Get() [1/2]
template<typename T > static T & testing::DefaultValue< T & >::Get () inline static
References testing::internal::BuiltInDefaultValue< T >::Get().
Get() [2/2]
template<typename T > static T & testing::DefaultValue< T & >::Get () inline static
References testing::internal::BuiltInDefaultValue< T >::Get().
IsSet() [1/2]
template<typename T > static bool testing::DefaultValue< T & >::IsSet () inline static
IsSet() [2/2]
template<typename T > static bool testing::DefaultValue< T & >::IsSet () inline static
Set() [1/2]
template<typename T > static void testing::DefaultValue< T & >::Set (T & x) inline static
Set() [2/2]
template<typename T > static void testing::DefaultValue< T & >::Set (T & x) inline static
The documentation for this class was generated from the following files:
dsd/test/gmock/include/gmock/gmock-actions.h
mbelib/test/gmock/include/gmock/gmock-actions.h