GNU Radio's DSD Package: testing::internal::UnorderedElementsAreMatcherImpl< Container > Class Template Reference
testing::internal::UnorderedElementsAreMatcherImpl< Container > Class Template Reference
#include <gmock-matchers.h>
Public Types
typedef internal::StlContainerView< RawContainer > View
typedef View::type StlContainer
typedef View::const_reference StlContainerReference
typedef StlContainer::const_iterator StlContainerConstIterator
typedef StlContainer::value_type Element
typedef internal::StlContainerView< RawContainer > View
typedef View::type StlContainer
typedef View::const_reference StlContainerReference
typedef StlContainer::const_iterator StlContainerConstIterator
typedef StlContainer::value_type Element
Public Member Functions
typedef GTEST_REMOVE_REFERENCE_AND_CONST_ (Container) RawContainer
template<typename InputIter >
UnorderedElementsAreMatcherImpl (InputIter first, InputIter last)
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
virtual bool MatchAndExplain (Container container, MatchResultListener *listener) const
typedef GTEST_REMOVE_REFERENCE_AND_CONST_ (Container) RawContainer
template<typename InputIter >
UnorderedElementsAreMatcherImpl (InputIter first, InputIter last)
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
virtual bool MatchAndExplain (Container container, MatchResultListener *listener) const
Public Member Functions inherited from testing::MatcherDescriberInterface
virtual ~MatcherDescriberInterface ()
virtual ~MatcherDescriberInterface ()
Additional Inherited Members
Protected Types inherited from testing::internal::UnorderedElementsAreMatcherImplBase
typedef ::std::vector< const MatcherDescriberInterface * > MatcherDescriberVec
typedef ::std::vector< const MatcherDescriberInterface * > MatcherDescriberVec
Protected Member Functions inherited from testing::internal::UnorderedElementsAreMatcherImplBase
void DescribeToImpl (::std::ostream *os) const
void DescribeNegationToImpl (::std::ostream *os) const
bool VerifyAllElementsAndMatchersAreMatched (const ::std::vector< string > &element_printouts, const MatchMatrix &matrix, MatchResultListener *listener) const
MatcherDescriberVec & matcher_describers ()
void DescribeToImpl (::std::ostream *os) const
void DescribeNegationToImpl (::std::ostream *os) const
bool VerifyAllElementsAndMatchersAreMatched (const ::std::vector< string > &element_printouts, const MatchMatrix &matrix, MatchResultListener *listener) const
MatcherDescriberVec & matcher_describers ()
Static Protected Member Functions inherited from testing::internal::UnorderedElementsAreMatcherImplBase
static Message Elements (size_t n)
static Message Elements (size_t n)
Member Typedef Documentation
Element [1/2]
template<typename Container > typedef StlContainer::value_type testing::internal::UnorderedElementsAreMatcherImpl< Container >::Element
Element [2/2]
template<typename Container > typedef StlContainer::value_type testing::internal::UnorderedElementsAreMatcherImpl< Container >::Element
StlContainer [1/2]
template<typename Container > typedef View::type testing::internal::UnorderedElementsAreMatcherImpl< Container >::StlContainer
StlContainer [2/2]
template<typename Container > typedef View::type testing::internal::UnorderedElementsAreMatcherImpl< Container >::StlContainer
StlContainerConstIterator [1/2]
template<typename Container > typedef StlContainer::const_iterator testing::internal::UnorderedElementsAreMatcherImpl< Container >::StlContainerConstIterator
StlContainerConstIterator [2/2]
template<typename Container > typedef StlContainer::const_iterator testing::internal::UnorderedElementsAreMatcherImpl< Container >::StlContainerConstIterator
StlContainerReference [1/2]
template<typename Container > typedef View::const_reference testing::internal::UnorderedElementsAreMatcherImpl< Container >::StlContainerReference
StlContainerReference [2/2]
template<typename Container > typedef View::const_reference testing::internal::UnorderedElementsAreMatcherImpl< Container >::StlContainerReference
View [1/2]
template<typename Container > typedef internal::StlContainerView<RawContainer> testing::internal::UnorderedElementsAreMatcherImpl< Container >::View
View [2/2]
template<typename Container > typedef internal::StlContainerView<RawContainer> testing::internal::UnorderedElementsAreMatcherImpl< Container >::View
Constructor & Destructor Documentation
UnorderedElementsAreMatcherImpl() [1/2]
template<typename Container > template<typename InputIter > testing::internal::UnorderedElementsAreMatcherImpl< Container >::UnorderedElementsAreMatcherImpl (InputIter first, InputIter last) inline
References testing::internal::UnorderedElementsAreMatcherImplBase::matcher_describers().
UnorderedElementsAreMatcherImpl() [2/2]
template<typename Container > template<typename InputIter > testing::internal::UnorderedElementsAreMatcherImpl< Container >::UnorderedElementsAreMatcherImpl (InputIter first, InputIter last) inline
References testing::internal::UnorderedElementsAreMatcherImplBase::matcher_describers().
Member Function Documentation
DescribeNegationTo() [1/2]
template<typename Container > virtual void testing::internal::UnorderedElementsAreMatcherImpl< Container >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
References testing::internal::UnorderedElementsAreMatcherImplBase::DescribeNegationToImpl().
DescribeNegationTo() [2/2]
template<typename Container > virtual void testing::internal::UnorderedElementsAreMatcherImpl< Container >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
References testing::internal::UnorderedElementsAreMatcherImplBase::DescribeNegationToImpl().
DescribeTo() [1/2]
template<typename Container > virtual void testing::internal::UnorderedElementsAreMatcherImpl< Container >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
References testing::internal::UnorderedElementsAreMatcherImplBase::DescribeToImpl().
DescribeTo() [2/2]
template<typename Container > virtual void testing::internal::UnorderedElementsAreMatcherImpl< Container >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
References testing::internal::UnorderedElementsAreMatcherImplBase::DescribeToImpl().
GTEST_REMOVE_REFERENCE_AND_CONST_() [1/2]
template<typename Container > typedef testing::internal::UnorderedElementsAreMatcherImpl< Container >::GTEST_REMOVE_REFERENCE_AND_CONST_ (Container)
GTEST_REMOVE_REFERENCE_AND_CONST_() [2/2]
template<typename Container > typedef testing::internal::UnorderedElementsAreMatcherImpl< Container >::GTEST_REMOVE_REFERENCE_AND_CONST_ (Container)
MatchAndExplain() [1/2]
template<typename Container > virtual bool testing::internal::UnorderedElementsAreMatcherImpl< Container >::MatchAndExplain (Container container, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< Container >.
References testing::internal::StlContainerView< RawContainer >::ConstReference(), testing::internal::UnorderedElementsAreMatcherImplBase::Elements(), testing::internal::FindPairing(), testing::MatchResultListener::IsInterested(), testing::internal::MatchMatrix::LhsSize(), and testing::internal::UnorderedElementsAreMatcherImplBase::VerifyAllElementsAndMatchersAreMatched().
MatchAndExplain() [2/2]
template<typename Container > virtual bool testing::internal::UnorderedElementsAreMatcherImpl< Container >::MatchAndExplain (Container container, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< Container >.
References testing::internal::StlContainerView< RawContainer >::ConstReference(), testing::internal::UnorderedElementsAreMatcherImplBase::Elements(), testing::internal::FindPairing(), testing::internal::MatchMatrix::LhsSize(), and testing::internal::UnorderedElementsAreMatcherImplBase::VerifyAllElementsAndMatchersAreMatched().
The documentation for this class was generated from the following files:
dsd/test/gmock/include/gmock/gmock-matchers.h
mbelib/test/gmock/include/gmock/gmock-matchers.h