GNU Radio's DSD Package: testing::internal::OnCallSpec< F > Class Template Reference
testing::internal::OnCallSpec< F > Class Template Reference
#include <gmock-spec-builders.h>
Public Types
typedef Function< F >::ArgumentTuple ArgumentTuple
typedef Function< F >::ArgumentMatcherTuple ArgumentMatcherTuple
typedef Function< F >::ArgumentTuple ArgumentTuple
typedef Function< F >::ArgumentMatcherTuple ArgumentMatcherTuple
Public Member Functions
OnCallSpec (const char *a_file, int a_line, const ArgumentMatcherTuple &matchers)
OnCallSpec & With (const Matcher< const ArgumentTuple & > &m)
OnCallSpec & WillByDefault (const Action< F > &action)
bool Matches (const ArgumentTuple &args) const
const Action< F > & GetAction () const
OnCallSpec (const char *a_file, int a_line, const ArgumentMatcherTuple &matchers)
OnCallSpec & With (const Matcher< const ArgumentTuple & > &m)
OnCallSpec & WillByDefault (const Action< F > &action)
bool Matches (const ArgumentTuple &args) const
const Action< F > & GetAction () const
Public Member Functions inherited from testing::internal::UntypedOnCallSpecBase
UntypedOnCallSpecBase (const char *a_file, int a_line)
const char * file () const
int line () const
UntypedOnCallSpecBase (const char *a_file, int a_line)
const char * file () const
int line () const
Additional Inherited Members
Protected Types inherited from testing::internal::UntypedOnCallSpecBase
enum Clause {
kNone , kWith , kWillByDefault , kNone ,
kWith , kWillByDefault
}
enum Clause {
kNone , kWith , kWillByDefault , kNone ,
kWith , kWillByDefault
}
Protected Member Functions inherited from testing::internal::UntypedOnCallSpecBase
void AssertSpecProperty (bool property, const string &failure_message) const
void ExpectSpecProperty (bool property, const string &failure_message) const
void AssertSpecProperty (bool property, const string &failure_message) const
void ExpectSpecProperty (bool property, const string &failure_message) const
Protected Attributes inherited from testing::internal::UntypedOnCallSpecBase
const char * file_
int line_
Clause last_clause_
Member Typedef Documentation
ArgumentMatcherTuple [1/2]
template<typename F > typedef Function<F>::ArgumentMatcherTuple testing::internal::OnCallSpec< F >::ArgumentMatcherTuple
ArgumentMatcherTuple [2/2]
template<typename F > typedef Function<F>::ArgumentMatcherTuple testing::internal::OnCallSpec< F >::ArgumentMatcherTuple
ArgumentTuple [1/2]
template<typename F > typedef Function<F>::ArgumentTuple testing::internal::OnCallSpec< F >::ArgumentTuple
ArgumentTuple [2/2]
template<typename F > typedef Function<F>::ArgumentTuple testing::internal::OnCallSpec< F >::ArgumentTuple
Constructor & Destructor Documentation
OnCallSpec() [1/2]
template<typename F > testing::internal::OnCallSpec< F >::OnCallSpec (const char * a_file, int a_line, const ArgumentMatcherTuple & matchers) inline
References testing::A().
OnCallSpec() [2/2]
template<typename F > testing::internal::OnCallSpec< F >::OnCallSpec (const char * a_file, int a_line, const ArgumentMatcherTuple & matchers) inline
References testing::A().
Member Function Documentation
GetAction() [1/2]
template<typename F > const Action< F > & testing::internal::OnCallSpec< F >::GetAction () const inline
Referenced by testing::internal::FunctionMockerBase< F >::PerformDefaultAction().
GetAction() [2/2]
template<typename F > const Action< F > & testing::internal::OnCallSpec< F >::GetAction () const inline
Matches() [1/2]
template<typename F > bool testing::internal::OnCallSpec< F >::Matches (const ArgumentTuple & args) const inline
References testing::internal::TupleMatches().
Referenced by testing::internal::FunctionMockerBase< F >::FindOnCallSpec().
Matches() [2/2]
template<typename F > bool testing::internal::OnCallSpec< F >::Matches (const ArgumentTuple & args) const inline
References testing::internal::TupleMatches().
WillByDefault() [1/2]
template<typename F > OnCallSpec & testing::internal::OnCallSpec< F >::WillByDefault (const Action< F > & action) inline
References testing::Action< F >::IsDoDefault().
WillByDefault() [2/2]
template<typename F > OnCallSpec & testing::internal::OnCallSpec< F >::WillByDefault (const Action< F > & action) inline
References testing::Action< F >::IsDoDefault().
With() [1/2]
template<typename F > OnCallSpec & testing::internal::OnCallSpec< F >::With (const Matcher< const ArgumentTuple & > & m) inline
With() [2/2]
template<typename F > OnCallSpec & testing::internal::OnCallSpec< F >::With (const Matcher< const ArgumentTuple & > & m) inline
The documentation for this class was generated from the following files:
dsd/test/gmock/include/gmock/gmock-spec-builders.h
mbelib/test/gmock/include/gmock/gmock-spec-builders.h