GNU Radio's DSD Package: testing::internal::TypedExpectation< F > Class Template Reference
testing::internal::TypedExpectation< F > Class Template Reference
Public Types
typedef Function< F >::ArgumentTuple ArgumentTuple
typedef Function< F >::ArgumentMatcherTuple ArgumentMatcherTuple
typedef Function< F >::Result Result
typedef Function< F >::ArgumentTuple ArgumentTuple
typedef Function< F >::ArgumentMatcherTuple ArgumentMatcherTuple
typedef Function< F >::Result Result
Public Member Functions
TypedExpectation (FunctionMockerBase< F > *owner, const char *a_file, int a_line, const string &a_source_text, const ArgumentMatcherTuple &m)
virtual ~TypedExpectation ()
TypedExpectation & With (const Matcher< const ArgumentTuple & > &m)
TypedExpectation & Times (const Cardinality &a_cardinality)
TypedExpectation & Times (int n)
TypedExpectation & InSequence (const Sequence &s)
TypedExpectation & InSequence (const Sequence &s1, const Sequence &s2)
TypedExpectation & InSequence (const Sequence &s1, const Sequence &s2, const Sequence &s3)
TypedExpectation & InSequence (const Sequence &s1, const Sequence &s2, const Sequence &s3, const Sequence &s4)
TypedExpectation & InSequence (const Sequence &s1, const Sequence &s2, const Sequence &s3, const Sequence &s4, const Sequence &s5)
TypedExpectation & After (const ExpectationSet &s)
TypedExpectation & After (const ExpectationSet &s1, const ExpectationSet &s2)
TypedExpectation & After (const ExpectationSet &s1, const ExpectationSet &s2, const ExpectationSet &s3)
TypedExpectation & After (const ExpectationSet &s1, const ExpectationSet &s2, const ExpectationSet &s3, const ExpectationSet &s4)
TypedExpectation & After (const ExpectationSet &s1, const ExpectationSet &s2, const ExpectationSet &s3, const ExpectationSet &s4, const ExpectationSet &s5)
TypedExpectation & WillOnce (const Action< F > &action)
TypedExpectation & WillRepeatedly (const Action< F > &action)
TypedExpectation & RetiresOnSaturation ()
const ArgumentMatcherTuple & matchers () const
const Matcher< const ArgumentTuple & > & extra_matcher () const
const Action< F > & repeated_action () const
virtual void MaybeDescribeExtraMatcherTo (::std::ostream *os)
TypedExpectation (FunctionMockerBase< F > *owner, const char *a_file, int a_line, const string &a_source_text, const ArgumentMatcherTuple &m)
virtual ~TypedExpectation ()
TypedExpectation & With (const Matcher< const ArgumentTuple & > &m)
TypedExpectation & Times (const Cardinality &a_cardinality)
TypedExpectation & Times (int n)
TypedExpectation & InSequence (const Sequence &s)
TypedExpectation & InSequence (const Sequence &s1, const Sequence &s2)
TypedExpectation & InSequence (const Sequence &s1, const Sequence &s2, const Sequence &s3)
TypedExpectation & InSequence (const Sequence &s1, const Sequence &s2, const Sequence &s3, const Sequence &s4)
TypedExpectation & InSequence (const Sequence &s1, const Sequence &s2, const Sequence &s3, const Sequence &s4, const Sequence &s5)
TypedExpectation & After (const ExpectationSet &s)
TypedExpectation & After (const ExpectationSet &s1, const ExpectationSet &s2)
TypedExpectation & After (const ExpectationSet &s1, const ExpectationSet &s2, const ExpectationSet &s3)
TypedExpectation & After (const ExpectationSet &s1, const ExpectationSet &s2, const ExpectationSet &s3, const ExpectationSet &s4)
TypedExpectation & After (const ExpectationSet &s1, const ExpectationSet &s2, const ExpectationSet &s3, const ExpectationSet &s4, const ExpectationSet &s5)
TypedExpectation & WillOnce (const Action< F > &action)
TypedExpectation & WillRepeatedly (const Action< F > &action)
TypedExpectation & RetiresOnSaturation ()
const ArgumentMatcherTuple & matchers () const
const Matcher< const ArgumentTuple & > & extra_matcher () const
const Action< F > & repeated_action () const
virtual void MaybeDescribeExtraMatcherTo (::std::ostream *os)
Friends
template<typename Function >
class FunctionMockerBase
template<typename Function >
class FunctionMockerBase
Member Typedef Documentation
ArgumentMatcherTuple [1/2]
template<typename F > typedef Function<F>::ArgumentMatcherTuple testing::internal::TypedExpectation< F >::ArgumentMatcherTuple
ArgumentMatcherTuple [2/2]
template<typename F > typedef Function<F>::ArgumentMatcherTuple testing::internal::TypedExpectation< F >::ArgumentMatcherTuple
ArgumentTuple [1/2]
template<typename F > typedef Function<F>::ArgumentTuple testing::internal::TypedExpectation< F >::ArgumentTuple
ArgumentTuple [2/2]
template<typename F > typedef Function<F>::ArgumentTuple testing::internal::TypedExpectation< F >::ArgumentTuple
Result [1/2]
template<typename F > typedef Function<F>::Result testing::internal::TypedExpectation< F >::Result
Result [2/2]
template<typename F > typedef Function<F>::Result testing::internal::TypedExpectation< F >::Result
Constructor & Destructor Documentation
TypedExpectation() [1/2]
template<typename F > testing::internal::TypedExpectation< F >::TypedExpectation (FunctionMockerBase< F > * owner, const char * a_file, int a_line, const string & a_source_text, const ArgumentMatcherTuple & m) inline
References testing::A(), and testing::DoDefault().
~TypedExpectation() [1/2]
template<typename F > virtual testing::internal::TypedExpectation< F >::~TypedExpectation () inline virtual
TypedExpectation() [2/2]
template<typename F > testing::internal::TypedExpectation< F >::TypedExpectation (FunctionMockerBase< F > * owner, const char * a_file, int a_line, const string & a_source_text, const ArgumentMatcherTuple & m) inline
References testing::A(), and testing::DoDefault().
~TypedExpectation() [2/2]
template<typename F > virtual testing::internal::TypedExpectation< F >::~TypedExpectation () inline virtual
Member Function Documentation
After() [1/10]
template<typename F > TypedExpectation & testing::internal::TypedExpectation< F >::After (const ExpectationSet & s) inline
References testing::ExpectationSet::begin(), and testing::ExpectationSet::end().
Referenced by testing::internal::TypedExpectation< F >::After(), testing::internal::TypedExpectation< F >::After(), testing::internal::TypedExpectation< F >::After(), and testing::internal::TypedExpectation< F >::After().
After() [2/10]
template<typename F > TypedExpectation & testing::internal::TypedExpectation< F >::After (const ExpectationSet & s) inline
After() [3/10]
template<typename F > TypedExpectation & testing::internal::TypedExpectation< F >::After (const ExpectationSet & s1, const ExpectationSet & s2) inline
References testing::internal::TypedExpectation< F >::After().
After() [4/10]
template<typename F > TypedExpectation & testing::internal::TypedExpectation< F >::After (const ExpectationSet & s1, const ExpectationSet & s2) inline
References testing::internal::TypedExpectation< F >::After().
After() [5/10]
template<typename F > TypedExpectation & testing::internal::TypedExpectation< F >::After (const ExpectationSet & s1, const ExpectationSet & s2, const ExpectationSet & s3) inline
References testing::internal::TypedExpectation< F >::After().
After() [6/10]
template<typename F > TypedExpectation & testing::internal::TypedExpectation< F >::After (const ExpectationSet & s1, const ExpectationSet & s2, const ExpectationSet & s3) inline
References testing::internal::TypedExpectation< F >::After().
After() [7/10]
template<typename F > TypedExpectation & testing::internal::TypedExpectation< F >::After (const ExpectationSet & s1, const ExpectationSet & s2, const ExpectationSet & s3, const ExpectationSet & s4) inline
References testing::internal::TypedExpectation< F >::After().
After() [8/10]
template<typename F > TypedExpectation & testing::internal::TypedExpectation< F >::After (const ExpectationSet & s1, const ExpectationSet & s2, const ExpectationSet & s3, const ExpectationSet & s4) inline
References testing::internal::TypedExpectation< F >::After().
After() [9/10]
template<typename F > TypedExpectation & testing::internal::TypedExpectation< F >::After (const ExpectationSet & s1, const ExpectationSet & s2, const ExpectationSet & s3, const ExpectationSet & s4, const ExpectationSet & s5) inline
References testing::internal::TypedExpectation< F >::After().
After() [10/10]
template<typename F > TypedExpectation & testing::internal::TypedExpectation< F >::After (const ExpectationSet & s1, const ExpectationSet & s2, const ExpectationSet & s3, const ExpectationSet & s4, const ExpectationSet & s5) inline
References testing::internal::TypedExpectation< F >::After().
extra_matcher() [1/2]
template<typename F > const Matcher< const ArgumentTuple & > & testing::internal::TypedExpectation< F >::extra_matcher () const inline
extra_matcher() [2/2]
template<typename F > const Matcher< const ArgumentTuple & > & testing::internal::TypedExpectation< F >::extra_matcher () const inline
InSequence() [1/10]
template<typename F > TypedExpectation & testing::internal::TypedExpectation< F >::InSequence (const Sequence & s) inline
References testing::Sequence::AddExpectation().
InSequence() [2/10]
template<typename F > TypedExpectation & testing::internal::TypedExpectation< F >::InSequence (const Sequence & s) inline
References testing::Sequence::AddExpectation().
InSequence() [3/10]
template<typename F > TypedExpectation & testing::internal::TypedExpectation< F >::InSequence (const Sequence & s1, const Sequence & s2) inline
References testing::InSequence::InSequence().
InSequence() [4/10]
template<typename F > TypedExpectation & testing::internal::TypedExpectation< F >::InSequence (const Sequence & s1, const Sequence & s2) inline
References testing::InSequence::InSequence().
InSequence() [5/10]
template<typename F > TypedExpectation & testing::internal::TypedExpectation< F >::InSequence (const Sequence & s1, const Sequence & s2, const Sequence & s3) inline
References testing::InSequence::InSequence().
InSequence() [6/10]
template<typename F > TypedExpectation & testing::internal::TypedExpectation< F >::InSequence (const Sequence & s1, const Sequence & s2, const Sequence & s3) inline
References testing::InSequence::InSequence().
InSequence() [7/10]
template<typename F > TypedExpectation & testing::internal::TypedExpectation< F >::InSequence (const Sequence & s1, const Sequence & s2, const Sequence & s3, const Sequence & s4) inline
References testing::InSequence::InSequence().
InSequence() [8/10]
template<typename F > TypedExpectation & testing::internal::TypedExpectation< F >::InSequence (const Sequence & s1, const Sequence & s2, const Sequence & s3, const Sequence & s4) inline
References testing::InSequence::InSequence().
InSequence() [9/10]
template<typename F > TypedExpectation & testing::internal::TypedExpectation< F >::InSequence (const Sequence & s1, const Sequence & s2, const Sequence & s3, const Sequence & s4, const Sequence & s5) inline
References testing::InSequence::InSequence().
InSequence() [10/10]
template<typename F > TypedExpectation & testing::internal::TypedExpectation< F >::InSequence (const Sequence & s1, const Sequence & s2, const Sequence & s3, const Sequence & s4, const Sequence & s5) inline
References testing::InSequence::InSequence().
matchers() [1/2]
template<typename F > const ArgumentMatcherTuple & testing::internal::TypedExpectation< F >::matchers () const inline
matchers() [2/2]
template<typename F > const ArgumentMatcherTuple & testing::internal::TypedExpectation< F >::matchers () const inline
MaybeDescribeExtraMatcherTo() [1/2]
template<typename F > virtual void testing::internal::TypedExpectation< F >::MaybeDescribeExtraMatcherTo (::std::ostream * os) inline virtual
MaybeDescribeExtraMatcherTo() [2/2]
template<typename F > virtual void testing::internal::TypedExpectation< F >::MaybeDescribeExtraMatcherTo (::std::ostream * os) inline virtual
repeated_action() [1/2]
template<typename F > const Action< F > & testing::internal::TypedExpectation< F >::repeated_action () const inline
repeated_action() [2/2]
template<typename F > const Action< F > & testing::internal::TypedExpectation< F >::repeated_action () const inline
RetiresOnSaturation() [1/2]
template<typename F > TypedExpectation & testing::internal::TypedExpectation< F >::RetiresOnSaturation () inline
RetiresOnSaturation() [2/2]
template<typename F > TypedExpectation & testing::internal::TypedExpectation< F >::RetiresOnSaturation () inline
Times() [1/4]
template<typename F > TypedExpectation & testing::internal::TypedExpectation< F >::Times (const Cardinality & a_cardinality) inline
Times() [2/4]
template<typename F > TypedExpectation & testing::internal::TypedExpectation< F >::Times (const Cardinality & a_cardinality) inline
Times() [3/4]
template<typename F > TypedExpectation & testing::internal::TypedExpectation< F >::Times (int n) inline
References testing::Exactly().
Times() [4/4]
template<typename F > TypedExpectation & testing::internal::TypedExpectation< F >::Times (int n) inline
References testing::Exactly().
WillOnce() [1/2]
template<typename F > TypedExpectation & testing::internal::TypedExpectation< F >::WillOnce (const Action< F > & action) inline
References testing::Exactly().
WillOnce() [2/2]
template<typename F > TypedExpectation & testing::internal::TypedExpectation< F >::WillOnce (const Action< F > & action) inline
References testing::Exactly().
WillRepeatedly() [1/2]
template<typename F > TypedExpectation & testing::internal::TypedExpectation< F >::WillRepeatedly (const Action< F > & action) inline
References testing::AtLeast().
WillRepeatedly() [2/2]
template<typename F > TypedExpectation & testing::internal::TypedExpectation< F >::WillRepeatedly (const Action< F > & action) inline
References testing::AtLeast().
With() [1/2]
template<typename F > TypedExpectation & testing::internal::TypedExpectation< F >::With (const Matcher< const ArgumentTuple & > & m) inline
With() [2/2]
template<typename F > TypedExpectation & testing::internal::TypedExpectation< F >::With (const Matcher< const ArgumentTuple & > & m) inline
Friends And Related Symbol Documentation
FunctionMockerBase [1/2]
template<typename F > template<typename Function > friend class FunctionMockerBase friend
FunctionMockerBase [2/2]
template<typename F > template<typename Function > class FunctionMockerBase friend
The documentation for this class was generated from the following files:
dsd/test/gmock/include/gmock/gmock-spec-builders.h
mbelib/test/gmock/include/gmock/gmock-spec-builders.h