GNU Radio's DSD Package: testing::internal::UnorderedElementsAreMatcher< MatcherTuple > Class Template Reference
testing::internal::UnorderedElementsAreMatcher< MatcherTuple > Class Template Reference
#include <gmock-matchers.h>
Public Member Functions
UnorderedElementsAreMatcher (const MatcherTuple &args)
template<typename Container >
operator Matcher< Container > () const
UnorderedElementsAreMatcher (const MatcherTuple &args)
template<typename Container >
operator Matcher< Container > () const
Constructor & Destructor Documentation
UnorderedElementsAreMatcher() [1/2]
template<typename MatcherTuple > testing::internal::UnorderedElementsAreMatcher< MatcherTuple >::UnorderedElementsAreMatcher (const MatcherTuple & args) inline explicit
UnorderedElementsAreMatcher() [2/2]
template<typename MatcherTuple > testing::internal::UnorderedElementsAreMatcher< MatcherTuple >::UnorderedElementsAreMatcher (const MatcherTuple & args) inline explicit
Member Function Documentation
operator Matcher< Container >() [1/2]
template<typename MatcherTuple > template<typename Container > testing::internal::UnorderedElementsAreMatcher< MatcherTuple >::operator Matcher< Container > () const inline
References GTEST_REMOVE_REFERENCE_AND_CONST_, testing::MakeMatcher(), and testing::internal::TransformTupleValues().
operator Matcher< Container >() [2/2]
template<typename MatcherTuple > template<typename Container > testing::internal::UnorderedElementsAreMatcher< MatcherTuple >::operator Matcher< Container > () const inline
References GTEST_REMOVE_REFERENCE_AND_CONST_, testing::MakeMatcher(), and testing::internal::TransformTupleValues().
The documentation for this class was generated from the following files:
dsd/test/gmock/include/gmock/gmock-matchers.h
mbelib/test/gmock/include/gmock/gmock-matchers.h