GNU Radio's DSD Package: testing::internal::scoped_ptr< T > Class Template Reference
testing::internal::scoped_ptr< T > Class Template Reference
#include <gtest-port.h>
Public Types
typedef T element_type
typedef T element_type
Public Member Functions
scoped_ptr (T *p=NULL)
~scoped_ptr ()
T & operator* () const
T * operator-> () const
T * get () const
T * release ()
void reset (T *p=NULL)
scoped_ptr (T *p=NULL)
~scoped_ptr ()
T & operator* () const
T * operator-> () const
T * get () const
T * release ()
void reset (T *p=NULL)
Member Typedef Documentation
element_type [1/2]
template<typename T > typedef T testing::internal::scoped_ptr< T >::element_type
element_type [2/2]
template<typename T > typedef T testing::internal::scoped_ptr< T >::element_type
Constructor & Destructor Documentation
scoped_ptr() [1/2]
template<typename T > testing::internal::scoped_ptr< T >::scoped_ptr (T * p = NULL) inline explicit
~scoped_ptr() [1/2]
template<typename T > testing::internal::scoped_ptr< T >::~scoped_ptr () inline
References testing::internal::scoped_ptr< T >::reset().
scoped_ptr() [2/2]
template<typename T > testing::internal::scoped_ptr< T >::scoped_ptr (T * p = NULL) inline explicit
~scoped_ptr() [2/2]
template<typename T > testing::internal::scoped_ptr< T >::~scoped_ptr () inline
References testing::internal::scoped_ptr< T >::reset().
Member Function Documentation
get() [1/2]
template<typename T > T * testing::internal::scoped_ptr< T >::get () const inline
get() [2/2]
template<typename T > T * testing::internal::scoped_ptr< T >::get () const inline
operator*() [1/2]
template<typename T > T & testing::internal::scoped_ptr< T >::operator* () const inline
operator*() [2/2]
template<typename T > T & testing::internal::scoped_ptr< T >::operator* () const inline
operator->() [1/2]
template<typename T > T * testing::internal::scoped_ptr< T >::operator-> () const inline
operator->() [2/2]
template<typename T > T * testing::internal::scoped_ptr< T >::operator-> () const inline
release() [1/2]
template<typename T > T * testing::internal::scoped_ptr< T >::release () inline
release() [2/2]
template<typename T > T * testing::internal::scoped_ptr< T >::release () inline
reset() [1/2]
template<typename T > void testing::internal::scoped_ptr< T >::reset (T * p = NULL) inline
References testing::internal::IsTrue().
Referenced by testing::internal::scoped_ptr< T >::~scoped_ptr().
reset() [2/2]
template<typename T > void testing::internal::scoped_ptr< T >::reset (T * p = NULL) inline
References testing::internal::IsTrue().
The documentation for this class was generated from the following files:
dsd/test/gtest/include/gtest/internal/gtest-port.h
mbelib/test/gtest/include/gtest/internal/gtest-port.h