GNU Radio's DSD Package: testing::internal::StartsWithMatcher< StringType > Class Template Reference
testing::internal::StartsWithMatcher< StringType > Class Template Reference
#include <gmock-matchers.h>
Public Member Functions
StartsWithMatcher (const StringType &prefix)
template<typename CharType >
bool MatchAndExplain (CharType *s, MatchResultListener *listener) const
template<typename MatcheeStringType >
bool MatchAndExplain (const MatcheeStringType &s, MatchResultListener *) const
void DescribeTo (::std::ostream *os) const
void DescribeNegationTo (::std::ostream *os) const
StartsWithMatcher (const StringType &prefix)
template<typename CharType >
bool MatchAndExplain (CharType *s, MatchResultListener *listener) const
template<typename MatcheeStringType >
bool MatchAndExplain (const MatcheeStringType &s, MatchResultListener *) const
void DescribeTo (::std::ostream *os) const
void DescribeNegationTo (::std::ostream *os) const
Constructor & Destructor Documentation
StartsWithMatcher() [1/2]
template<typename StringType > testing::internal::StartsWithMatcher< StringType >::StartsWithMatcher (const StringType & prefix) inline explicit
StartsWithMatcher() [2/2]
template<typename StringType > testing::internal::StartsWithMatcher< StringType >::StartsWithMatcher (const StringType & prefix) inline explicit
Member Function Documentation
DescribeNegationTo() [1/2]
template<typename StringType > void testing::internal::StartsWithMatcher< StringType >::DescribeNegationTo (::std::ostream * os) const inline
References testing::internal::UniversalPrint().
DescribeNegationTo() [2/2]
template<typename StringType > void testing::internal::StartsWithMatcher< StringType >::DescribeNegationTo (::std::ostream * os) const inline
References testing::internal::UniversalPrint().
DescribeTo() [1/2]
template<typename StringType > void testing::internal::StartsWithMatcher< StringType >::DescribeTo (::std::ostream * os) const inline
References testing::internal::UniversalPrint().
DescribeTo() [2/2]
template<typename StringType > void testing::internal::StartsWithMatcher< StringType >::DescribeTo (::std::ostream * os) const inline
References testing::internal::UniversalPrint().
MatchAndExplain() [1/4]
template<typename StringType > template<typename CharType > bool testing::internal::StartsWithMatcher< StringType >::MatchAndExplain (CharType * s, MatchResultListener * listener) const inline
References testing::internal::StartsWithMatcher< StringType >::MatchAndExplain().
Referenced by testing::internal::StartsWithMatcher< StringType >::MatchAndExplain().
MatchAndExplain() [2/4]
template<typename StringType > template<typename CharType > bool testing::internal::StartsWithMatcher< StringType >::MatchAndExplain (CharType * s, MatchResultListener * listener) const inline
References testing::internal::StartsWithMatcher< StringType >::MatchAndExplain().
MatchAndExplain() [3/4]
template<typename StringType > template<typename MatcheeStringType > bool testing::internal::StartsWithMatcher< StringType >::MatchAndExplain (const MatcheeStringType & s, MatchResultListener *) const inline
MatchAndExplain() [4/4]
template<typename StringType > template<typename MatcheeStringType > bool testing::internal::StartsWithMatcher< StringType >::MatchAndExplain (const MatcheeStringType & s, MatchResultListener *) const inline
The documentation for this class was generated from the following files:
dsd/test/gmock/include/gmock/gmock-matchers.h
mbelib/test/gmock/include/gmock/gmock-matchers.h