GNU Radio's DSD Package: testing::internal::FloatingEqMatcher< FloatType > Class Template Reference
testing::internal::FloatingEqMatcher< FloatType > Class Template Reference
#include <gmock-matchers.h>
Classes
class Impl
Public Member Functions
FloatingEqMatcher (FloatType rhs, bool nan_eq_nan)
FloatingEqMatcher (FloatType rhs, bool nan_eq_nan, FloatType max_abs_error)
operator Matcher< FloatType > () const
operator Matcher< const FloatType & > () const
operator Matcher< FloatType & > () const
FloatingEqMatcher (FloatType rhs, bool nan_eq_nan)
FloatingEqMatcher (FloatType rhs, bool nan_eq_nan, FloatType max_abs_error)
operator Matcher< FloatType > () const
operator Matcher< const FloatType & > () const
operator Matcher< FloatType & > () const
Constructor & Destructor Documentation
FloatingEqMatcher() [1/4]
template<typename FloatType > testing::internal::FloatingEqMatcher< FloatType >::FloatingEqMatcher (FloatType rhs, bool nan_eq_nan) inline
FloatingEqMatcher() [2/4]
template<typename FloatType > testing::internal::FloatingEqMatcher< FloatType >::FloatingEqMatcher (FloatType rhs, bool nan_eq_nan, FloatType max_abs_error) inline
References GTEST_CHECK_.
FloatingEqMatcher() [3/4]
template<typename FloatType > testing::internal::FloatingEqMatcher< FloatType >::FloatingEqMatcher (FloatType rhs, bool nan_eq_nan) inline
FloatingEqMatcher() [4/4]
template<typename FloatType > testing::internal::FloatingEqMatcher< FloatType >::FloatingEqMatcher (FloatType rhs, bool nan_eq_nan, FloatType max_abs_error) inline
References GTEST_CHECK_.
Member Function Documentation
operator Matcher< const FloatType & >() [1/2]
template<typename FloatType > testing::internal::FloatingEqMatcher< FloatType >::operator Matcher< const FloatType & > () const inline
References testing::MakeMatcher().
operator Matcher< const FloatType & >() [2/2]
template<typename FloatType > testing::internal::FloatingEqMatcher< FloatType >::operator Matcher< const FloatType & > () const inline
References testing::MakeMatcher().
operator Matcher< FloatType & >() [1/2]
template<typename FloatType > testing::internal::FloatingEqMatcher< FloatType >::operator Matcher< FloatType & > () const inline
References testing::MakeMatcher().
operator Matcher< FloatType & >() [2/2]
template<typename FloatType > testing::internal::FloatingEqMatcher< FloatType >::operator Matcher< FloatType & > () const inline
References testing::MakeMatcher().
operator Matcher< FloatType >() [1/2]
template<typename FloatType > testing::internal::FloatingEqMatcher< FloatType >::operator Matcher< FloatType > () const inline
References testing::MakeMatcher().
operator Matcher< FloatType >() [2/2]
template<typename FloatType > testing::internal::FloatingEqMatcher< FloatType >::operator Matcher< FloatType > () const inline
References testing::MakeMatcher().
The documentation for this class was generated from the following files:
dsd/test/gmock/include/gmock/gmock-matchers.h
mbelib/test/gmock/include/gmock/gmock-matchers.h