GNU Radio's DSD Package: testing::internal::CallableHelper< R > Class Template Reference
testing::internal::CallableHelper< R > Class Template Reference
#include <gmock-generated-actions.h>
Static Public Member Functions
template<typename Function >
static R Call (Function function)
template<typename Function , typename A1 >
static R Call (Function function, A1 a1)
template<typename Function , typename A1 , typename A2 >
static R Call (Function function, A1 a1, A2 a2)
template<typename Function , typename A1 , typename A2 , typename A3 >
static R Call (Function function, A1 a1, A2 a2, A3 a3)
template<typename Function , typename A1 , typename A2 , typename A3 , typename A4 >
static R Call (Function function, A1 a1, A2 a2, A3 a3, A4 a4)
template<typename Function , typename A1 , typename A2 , typename A3 , typename A4 , typename A5 >
static R Call (Function function, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5)
template<typename Function , typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 >
static R Call (Function function, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6)
template<typename Function , typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 >
static R Call (Function function, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7)
template<typename Function , typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 >
static R Call (Function function, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8)
template<typename Function , typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 , typename A9 >
static R Call (Function function, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8, A9 a9)
template<typename Function , typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 , typename A9 , typename A10 >
static R Call (Function function, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8, A9 a9, A10 a10)
template<typename Function >
static R Call (Function function)
template<typename Function , typename A1 >
static R Call (Function function, A1 a1)
template<typename Function , typename A1 , typename A2 >
static R Call (Function function, A1 a1, A2 a2)
template<typename Function , typename A1 , typename A2 , typename A3 >
static R Call (Function function, A1 a1, A2 a2, A3 a3)
template<typename Function , typename A1 , typename A2 , typename A3 , typename A4 >
static R Call (Function function, A1 a1, A2 a2, A3 a3, A4 a4)
template<typename Function , typename A1 , typename A2 , typename A3 , typename A4 , typename A5 >
static R Call (Function function, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5)
template<typename Function , typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 >
static R Call (Function function, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6)
template<typename Function , typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 >
static R Call (Function function, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7)
template<typename Function , typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 >
static R Call (Function function, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8)
template<typename Function , typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 , typename A9 >
static R Call (Function function, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8, A9 a9)
template<typename Function , typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 , typename A9 , typename A10 >
static R Call (Function function, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8, A9 a9, A10 a10)
Member Function Documentation
Call() [1/22]
template<typename R > template<typename Function > static R testing::internal::CallableHelper< R >::Call (Function function) inline static
Referenced by testing::ACTION_TEMPLATE(), testing::ACTION_TEMPLATE(), testing::ACTION_TEMPLATE(), testing::ACTION_TEMPLATE(), testing::ACTION_TEMPLATE(), testing::ACTION_TEMPLATE(), testing::ACTION_TEMPLATE(), testing::ACTION_TEMPLATE(), testing::ACTION_TEMPLATE(), testing::ACTION_TEMPLATE(), and testing::ACTION_TEMPLATE().
Call() [2/22]
template<typename R > template<typename Function > static R testing::internal::CallableHelper< R >::Call (Function function) inline static
Call() [3/22]
template<typename R > template<typename Function , typename A1 > static R testing::internal::CallableHelper< R >::Call (Function function, A1 a1) inline static
Call() [4/22]
template<typename R > template<typename Function , typename A1 > static R testing::internal::CallableHelper< R >::Call (Function function, A1 a1) inline static
Call() [5/22]
template<typename R > template<typename Function , typename A1 , typename A2 > static R testing::internal::CallableHelper< R >::Call (Function function, A1 a1, A2 a2) inline static
Call() [6/22]
template<typename R > template<typename Function , typename A1 , typename A2 > static R testing::internal::CallableHelper< R >::Call (Function function, A1 a1, A2 a2) inline static
Call() [7/22]
template<typename R > template<typename Function , typename A1 , typename A2 , typename A3 > static R testing::internal::CallableHelper< R >::Call (Function function, A1 a1, A2 a2, A3 a3) inline static
Call() [8/22]
template<typename R > template<typename Function , typename A1 , typename A2 , typename A3 > static R testing::internal::CallableHelper< R >::Call (Function function, A1 a1, A2 a2, A3 a3) inline static
Call() [9/22]
template<typename R > template<typename Function , typename A1 , typename A2 , typename A3 , typename A4 > static R testing::internal::CallableHelper< R >::Call (Function function, A1 a1, A2 a2, A3 a3, A4 a4) inline static
Call() [10/22]
template<typename R > template<typename Function , typename A1 , typename A2 , typename A3 , typename A4 > static R testing::internal::CallableHelper< R >::Call (Function function, A1 a1, A2 a2, A3 a3, A4 a4) inline static
Call() [11/22]
template<typename R > template<typename Function , typename A1 , typename A2 , typename A3 , typename A4 , typename A5 > static R testing::internal::CallableHelper< R >::Call (Function function, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5) inline static
Call() [12/22]
template<typename R > template<typename Function , typename A1 , typename A2 , typename A3 , typename A4 , typename A5 > static R testing::internal::CallableHelper< R >::Call (Function function, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5) inline static
Call() [13/22]
template<typename R > template<typename Function , typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 > static R testing::internal::CallableHelper< R >::Call (Function function, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6) inline static
Call() [14/22]
template<typename R > template<typename Function , typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 > static R testing::internal::CallableHelper< R >::Call (Function function, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6) inline static
Call() [15/22]
template<typename R > template<typename Function , typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 > static R testing::internal::CallableHelper< R >::Call (Function function, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7) inline static
Call() [16/22]
template<typename R > template<typename Function , typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 > static R testing::internal::CallableHelper< R >::Call (Function function, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7) inline static
Call() [17/22]
template<typename R > template<typename Function , typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 > static R testing::internal::CallableHelper< R >::Call (Function function, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8) inline static
Call() [18/22]
template<typename R > template<typename Function , typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 > static R testing::internal::CallableHelper< R >::Call (Function function, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8) inline static
Call() [19/22]
template<typename R > template<typename Function , typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 , typename A9 > static R testing::internal::CallableHelper< R >::Call (Function function, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8, A9 a9) inline static
Call() [20/22]
template<typename R > template<typename Function , typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 , typename A9 > static R testing::internal::CallableHelper< R >::Call (Function function, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8, A9 a9) inline static
Call() [21/22]
template<typename R > template<typename Function , typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 , typename A9 , typename A10 > static R testing::internal::CallableHelper< R >::Call (Function function, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8, A9 a9, A10 a10) inline static
Call() [22/22]
template<typename R > template<typename Function , typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 , typename A9 , typename A10 > static R testing::internal::CallableHelper< R >::Call (Function function, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8, A9 a9, A10 a10) inline static
The documentation for this class was generated from the following files:
dsd/test/gmock/include/gmock/gmock-generated-actions.h
mbelib/test/gmock/include/gmock/gmock-generated-actions.h