GNU Radio's DSD Package: testing::MatcherDescriberInterface Class Reference
testing::MatcherDescriberInterface Class Reference abstract
#include <gmock-matchers.h>
Public Member Functions
virtual ~MatcherDescriberInterface ()
virtual void DescribeTo (::std::ostream *os) const =0
virtual void DescribeNegationTo (::std::ostream *os) const
virtual ~MatcherDescriberInterface ()
virtual void DescribeTo (::std::ostream *os) const =0
virtual void DescribeNegationTo (::std::ostream *os) const
Constructor & Destructor Documentation
~MatcherDescriberInterface() [1/2]
virtual testing::MatcherDescriberInterface::~MatcherDescriberInterface () inline virtual
~MatcherDescriberInterface() [2/2]
virtual testing::MatcherDescriberInterface::~MatcherDescriberInterface () inline virtual
Member Function Documentation
DescribeNegationTo() [1/2]
virtual void testing::MatcherDescriberInterface::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented in testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >, testing::internal::AnyMatcherImpl< T >, testing::internal::NotMatcherImpl< T >, testing::internal::BothOfMatcherImpl< T >, testing::internal::EitherOfMatcherImpl< T >, testing::internal::FloatingEqMatcher< FloatType >::Impl< T >, testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >, testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::Impl< LhsContainer >, testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >, testing::internal::ContainsMatcherImpl< Container >, testing::internal::EachMatcherImpl< Container >, testing::internal::KeyMatcherImpl< PairType >, testing::internal::PairMatcherImpl< PairType >, testing::internal::ElementsAreMatcherImpl< Container >, testing::internal::UnorderedElementsAreMatcherImpl< Container >, testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >, testing::internal::AnyMatcherImpl< T >, testing::internal::NotMatcherImpl< T >, testing::internal::BothOfMatcherImpl< T >, testing::internal::EitherOfMatcherImpl< T >, testing::internal::FloatingEqMatcher< FloatType >::Impl< T >, testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >, testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::Impl< LhsContainer >, testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >, testing::internal::ContainsMatcherImpl< Container >, testing::internal::EachMatcherImpl< Container >, testing::internal::KeyMatcherImpl< PairType >, testing::internal::PairMatcherImpl< PairType >, testing::internal::ElementsAreMatcherImpl< Container >, and testing::internal::UnorderedElementsAreMatcherImpl< Container >.
References DescribeTo().
DescribeNegationTo() [2/2]
virtual void testing::MatcherDescriberInterface::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented in testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >, testing::internal::AnyMatcherImpl< T >, testing::internal::NotMatcherImpl< T >, testing::internal::BothOfMatcherImpl< T >, testing::internal::EitherOfMatcherImpl< T >, testing::internal::FloatingEqMatcher< FloatType >::Impl< T >, testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >, testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::Impl< LhsContainer >, testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >, testing::internal::ContainsMatcherImpl< Container >, testing::internal::EachMatcherImpl< Container >, testing::internal::KeyMatcherImpl< PairType >, testing::internal::PairMatcherImpl< PairType >, testing::internal::ElementsAreMatcherImpl< Container >, testing::internal::UnorderedElementsAreMatcherImpl< Container >, testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >, testing::internal::AnyMatcherImpl< T >, testing::internal::NotMatcherImpl< T >, testing::internal::BothOfMatcherImpl< T >, testing::internal::EitherOfMatcherImpl< T >, testing::internal::FloatingEqMatcher< FloatType >::Impl< T >, testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >, testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::Impl< LhsContainer >, testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >, testing::internal::ContainsMatcherImpl< Container >, testing::internal::EachMatcherImpl< Container >, testing::internal::KeyMatcherImpl< PairType >, testing::internal::PairMatcherImpl< PairType >, testing::internal::ElementsAreMatcherImpl< Container >, and testing::internal::UnorderedElementsAreMatcherImpl< Container >.
References DescribeTo().
DescribeTo() [1/2]
virtual void testing::MatcherDescriberInterface::DescribeTo (::std::ostream * os) const pure virtual
Implemented in testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >, testing::internal::AnyMatcherImpl< T >, testing::internal::NotMatcherImpl< T >, testing::internal::BothOfMatcherImpl< T >, testing::internal::EitherOfMatcherImpl< T >, testing::internal::FloatingEqMatcher< FloatType >::Impl< T >, testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >, testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::Impl< LhsContainer >, testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >, testing::internal::ContainsMatcherImpl< Container >, testing::internal::EachMatcherImpl< Container >, testing::internal::KeyMatcherImpl< PairType >, testing::internal::PairMatcherImpl< PairType >, testing::internal::ElementsAreMatcherImpl< Container >, testing::internal::UnorderedElementsAreMatcherImpl< Container >, testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >, testing::internal::AnyMatcherImpl< T >, testing::internal::NotMatcherImpl< T >, testing::internal::BothOfMatcherImpl< T >, testing::internal::EitherOfMatcherImpl< T >, testing::internal::FloatingEqMatcher< FloatType >::Impl< T >, testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >, testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::Impl< LhsContainer >, testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >, testing::internal::ContainsMatcherImpl< Container >, testing::internal::EachMatcherImpl< Container >, testing::internal::KeyMatcherImpl< PairType >, testing::internal::PairMatcherImpl< PairType >, testing::internal::ElementsAreMatcherImpl< Container >, and testing::internal::UnorderedElementsAreMatcherImpl< Container >.
Referenced by DescribeNegationTo().
DescribeTo() [2/2]
virtual void testing::MatcherDescriberInterface::DescribeTo (::std::ostream * os) const pure virtual
Implemented in testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >, testing::internal::AnyMatcherImpl< T >, testing::internal::NotMatcherImpl< T >, testing::internal::BothOfMatcherImpl< T >, testing::internal::EitherOfMatcherImpl< T >, testing::internal::FloatingEqMatcher< FloatType >::Impl< T >, testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >, testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::Impl< LhsContainer >, testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >, testing::internal::ContainsMatcherImpl< Container >, testing::internal::EachMatcherImpl< Container >, testing::internal::KeyMatcherImpl< PairType >, testing::internal::PairMatcherImpl< PairType >, testing::internal::ElementsAreMatcherImpl< Container >, testing::internal::UnorderedElementsAreMatcherImpl< Container >, testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >, testing::internal::AnyMatcherImpl< T >, testing::internal::NotMatcherImpl< T >, testing::internal::BothOfMatcherImpl< T >, testing::internal::EitherOfMatcherImpl< T >, testing::internal::FloatingEqMatcher< FloatType >::Impl< T >, testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >, testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::Impl< LhsContainer >, testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >, testing::internal::ContainsMatcherImpl< Container >, testing::internal::EachMatcherImpl< Container >, testing::internal::KeyMatcherImpl< PairType >, testing::internal::PairMatcherImpl< PairType >, testing::internal::ElementsAreMatcherImpl< Container >, and testing::internal::UnorderedElementsAreMatcherImpl< Container >.
The documentation for this class was generated from the following files:
dsd/test/gmock/include/gmock/gmock-matchers.h
mbelib/test/gmock/include/gmock/gmock-matchers.h