GNU Radio's DSD Package: testing::internal::FunctionMockerBase< F > Class Template Reference
testing::internal::FunctionMockerBase< F > Class Template Reference
Public Types
typedef Function< F >::Result Result
typedef Function< F >::ArgumentTuple ArgumentTuple
typedef Function< F >::ArgumentMatcherTuple ArgumentMatcherTuple
typedef Function< F >::Result Result
typedef Function< F >::ArgumentTuple ArgumentTuple
typedef Function< F >::ArgumentMatcherTuple ArgumentMatcherTuple
Public Member Functions
FunctionMockerBase ()
virtual ~FunctionMockerBase () GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
const OnCallSpec< F > * FindOnCallSpec (const ArgumentTuple &args) const
Result PerformDefaultAction (const ArgumentTuple &args, const string &call_description) const
virtual UntypedActionResultHolderBase * UntypedPerformDefaultAction (const void *untyped_args, const string &call_description) const
virtual UntypedActionResultHolderBase * UntypedPerformAction (const void *untyped_action, const void *untyped_args) const
virtual void ClearDefaultActionsLocked () GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
FunctionMockerBase ()
virtual ~FunctionMockerBase () GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
const OnCallSpec< F > * FindOnCallSpec (const ArgumentTuple &args) const
Result PerformDefaultAction (const ArgumentTuple &args, const string &call_description) const
virtual UntypedActionResultHolderBase * UntypedPerformDefaultAction (const void *untyped_args, const string &call_description) const
virtual UntypedActionResultHolderBase * UntypedPerformAction (const void *untyped_action, const void *untyped_args) const
virtual void ClearDefaultActionsLocked () GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
Public Member Functions inherited from testing::internal::UntypedFunctionMockerBase
UntypedFunctionMockerBase ()
virtual ~UntypedFunctionMockerBase ()
bool VerifyAndClearExpectationsLocked () GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
void RegisterOwner (const void *mock_obj) GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
void SetOwnerAndName (const void *mock_obj, const char *name) GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
const void * MockObject () const GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
const char * Name () const GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
const UntypedActionResultHolderBase * UntypedInvokeWith (const void *untyped_args) GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
UntypedFunctionMockerBase ()
virtual ~UntypedFunctionMockerBase ()
bool VerifyAndClearExpectationsLocked () GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
void RegisterOwner (const void *mock_obj) GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
void SetOwnerAndName (const void *mock_obj, const char *name) GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
const void * MockObject () const GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
const char * Name () const GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
const UntypedActionResultHolderBase * UntypedInvokeWith (const void *untyped_args) GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
Protected Types
typedef ActionResultHolder< Result > ResultHolder
typedef ActionResultHolder< Result > ResultHolder
Protected Types inherited from testing::internal::UntypedFunctionMockerBase
typedef std::vector< const void * > UntypedOnCallSpecs
typedef std::vector< internal::linked_ptr< ExpectationBase > > UntypedExpectations
typedef std::vector< const void * > UntypedOnCallSpecs
typedef std::vector< internal::linked_ptr< ExpectationBase > > UntypedExpectations
Protected Member Functions
Result InvokeWith (const ArgumentTuple &args) GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
OnCallSpec< F > & AddNewOnCallSpec (const char *file, int line, const ArgumentMatcherTuple &m) GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
TypedExpectation< F > & AddNewExpectation (const char *file, int line, const string &source_text, const ArgumentMatcherTuple &m) GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
MockSpec< F > & current_spec ()
Result InvokeWith (const ArgumentTuple &args) GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
OnCallSpec< F > & AddNewOnCallSpec (const char *file, int line, const ArgumentMatcherTuple &m) GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
TypedExpectation< F > & AddNewExpectation (const char *file, int line, const string &source_text, const ArgumentMatcherTuple &m) GTEST_LOCK_EXCLUDED_(g_gmock_mutex)
MockSpec< F > & current_spec ()
Protected Member Functions inherited from testing::internal::UntypedFunctionMockerBase
Expectation GetHandleOf (ExpectationBase *exp)
Expectation GetHandleOf (ExpectationBase *exp)
Friends
template<typename Function >
class MockSpec
template<typename Func >
class TypedExpectation
template<typename Function >
class MockSpec
template<typename Func >
class TypedExpectation
Additional Inherited Members
Protected Attributes inherited from testing::internal::UntypedFunctionMockerBase
const void * mock_obj_
const char * name_
UntypedOnCallSpecs untyped_on_call_specs_
UntypedExpectations untyped_expectations_
Member Typedef Documentation
ArgumentMatcherTuple [1/2]
template<typename F > typedef Function<F>::ArgumentMatcherTuple testing::internal::FunctionMockerBase< F >::ArgumentMatcherTuple
ArgumentMatcherTuple [2/2]
template<typename F > typedef Function<F>::ArgumentMatcherTuple testing::internal::FunctionMockerBase< F >::ArgumentMatcherTuple
ArgumentTuple [1/2]
template<typename F > typedef Function<F>::ArgumentTuple testing::internal::FunctionMockerBase< F >::ArgumentTuple
ArgumentTuple [2/2]
template<typename F > typedef Function<F>::ArgumentTuple testing::internal::FunctionMockerBase< F >::ArgumentTuple
Result [1/2]
template<typename F > typedef Function<F>::Result testing::internal::FunctionMockerBase< F >::Result
Result [2/2]
template<typename F > typedef Function<F>::Result testing::internal::FunctionMockerBase< F >::Result
ResultHolder [1/2]
template<typename F > typedef ActionResultHolder<Result> testing::internal::FunctionMockerBase< F >::ResultHolder protected
ResultHolder [2/2]
template<typename F > typedef ActionResultHolder<Result> testing::internal::FunctionMockerBase< F >::ResultHolder protected
Constructor & Destructor Documentation
FunctionMockerBase() [1/2]
template<typename F > testing::internal::FunctionMockerBase< F >::FunctionMockerBase () inline
~FunctionMockerBase() [1/2]
template<typename F > virtual testing::internal::FunctionMockerBase< F >::~FunctionMockerBase () inline virtual
FunctionMockerBase() [2/2]
template<typename F > testing::internal::FunctionMockerBase< F >::FunctionMockerBase () inline
~FunctionMockerBase() [2/2]
template<typename F > virtual testing::internal::FunctionMockerBase< F >::~FunctionMockerBase () inline virtual
Member Function Documentation
AddNewExpectation() [1/2]
template<typename F > TypedExpectation< F > & testing::internal::FunctionMockerBase< F >::AddNewExpectation (const char * file, int line, const string & source_text, const ArgumentMatcherTuple & m) inline protected
References testing::Sequence::AddExpectation().
AddNewExpectation() [2/2]
template<typename F > TypedExpectation< F > & testing::internal::FunctionMockerBase< F >::AddNewExpectation (const char * file, int line, const string & source_text, const ArgumentMatcherTuple & m) inline protected
References testing::Sequence::AddExpectation().
AddNewOnCallSpec() [1/2]
template<typename F > OnCallSpec< F > & testing::internal::FunctionMockerBase< F >::AddNewOnCallSpec (const char * file, int line, const ArgumentMatcherTuple & m) inline protected
AddNewOnCallSpec() [2/2]
template<typename F > OnCallSpec< F > & testing::internal::FunctionMockerBase< F >::AddNewOnCallSpec (const char * file, int line, const ArgumentMatcherTuple & m) inline protected
ClearDefaultActionsLocked() [1/2]
template<typename F > virtual void testing::internal::FunctionMockerBase< F >::ClearDefaultActionsLocked () inline virtual
Implements testing::internal::UntypedFunctionMockerBase.
ClearDefaultActionsLocked() [2/2]
template<typename F > virtual void testing::internal::FunctionMockerBase< F >::ClearDefaultActionsLocked () inline virtual
Implements testing::internal::UntypedFunctionMockerBase.
current_spec() [1/2]
template<typename F > MockSpec< F > & testing::internal::FunctionMockerBase< F >::current_spec () inline protected
current_spec() [2/2]
template<typename F > MockSpec< F > & testing::internal::FunctionMockerBase< F >::current_spec () inline protected
FindOnCallSpec() [1/2]
template<typename F > const OnCallSpec< F > * testing::internal::FunctionMockerBase< F >::FindOnCallSpec (const ArgumentTuple & args) const inline
References testing::internal::OnCallSpec< F >::Matches().
FindOnCallSpec() [2/2]
template<typename F > const OnCallSpec< F > * testing::internal::FunctionMockerBase< F >::FindOnCallSpec (const ArgumentTuple & args) const inline
InvokeWith() [1/2]
template<typename F > Result testing::internal::FunctionMockerBase< F >::InvokeWith (const ArgumentTuple & args) inline protected
InvokeWith() [2/2]
template<typename F > Result testing::internal::FunctionMockerBase< F >::InvokeWith (const ArgumentTuple & args) inline protected
PerformDefaultAction() [1/2]
template<typename F > Result testing::internal::FunctionMockerBase< F >::PerformDefaultAction (const ArgumentTuple & args, const string & call_description) const inline
References testing::internal::Assert(), and testing::internal::OnCallSpec< F >::GetAction().
PerformDefaultAction() [2/2]
template<typename F > Result testing::internal::FunctionMockerBase< F >::PerformDefaultAction (const ArgumentTuple & args, const string & call_description) const inline
References testing::internal::Assert().
UntypedPerformAction() [1/2]
template<typename F > virtual UntypedActionResultHolderBase * testing::internal::FunctionMockerBase< F >::UntypedPerformAction (const void * untyped_action, const void * untyped_args) const inline virtual
Implements testing::internal::UntypedFunctionMockerBase.
UntypedPerformAction() [2/2]
template<typename F > virtual UntypedActionResultHolderBase * testing::internal::FunctionMockerBase< F >::UntypedPerformAction (const void * untyped_action, const void * untyped_args) const inline virtual
Implements testing::internal::UntypedFunctionMockerBase.
UntypedPerformDefaultAction() [1/2]
template<typename F > virtual UntypedActionResultHolderBase * testing::internal::FunctionMockerBase< F >::UntypedPerformDefaultAction (const void * untyped_args, const string & call_description) const inline virtual
Implements testing::internal::UntypedFunctionMockerBase.
UntypedPerformDefaultAction() [2/2]
template<typename F > virtual UntypedActionResultHolderBase * testing::internal::FunctionMockerBase< F >::UntypedPerformDefaultAction (const void * untyped_args, const string & call_description) const inline virtual
Implements testing::internal::UntypedFunctionMockerBase.
Friends And Related Symbol Documentation
MockSpec [1/2]
template<typename F > template<typename Function > friend class MockSpec friend
MockSpec [2/2]
template<typename F > template<typename Function > class MockSpec friend
TypedExpectation [1/2]
template<typename F > template<typename Func > friend class TypedExpectation friend
TypedExpectation [2/2]
template<typename F > template<typename Func > class TypedExpectation friend
The documentation for this class was generated from the following files:
dsd/test/gmock/include/gmock/gmock-generated-function-mockers.h
dsd/test/gmock/include/gmock/gmock-spec-builders.h
mbelib/test/gmock/include/gmock/gmock-spec-builders.h