GNU Radio's DSD Package: testing::internal::BuiltInDefaultValue< const T > Class Template Reference
testing::internal::BuiltInDefaultValue< const T > Class Template Reference
#include <gmock-actions.h>
Static Public Member Functions
static bool Exists ()
static T Get ()
static bool Exists ()
static T Get ()
Member Function Documentation
Exists() [1/2]
template<typename T > static bool testing::internal::BuiltInDefaultValue< const T >::Exists () inline static
References testing::internal::BuiltInDefaultValue< T >::Exists().
Exists() [2/2]
template<typename T > static bool testing::internal::BuiltInDefaultValue< const T >::Exists () inline static
References testing::internal::BuiltInDefaultValue< T >::Exists().
Get() [1/2]
template<typename T > static T testing::internal::BuiltInDefaultValue< const T >::Get () inline static
References testing::internal::BuiltInDefaultValue< T >::Get().
Get() [2/2]
template<typename T > static T testing::internal::BuiltInDefaultValue< const T >::Get () inline static
References testing::internal::BuiltInDefaultValue< T >::Get().
The documentation for this class was generated from the following files:
dsd/test/gmock/include/gmock/gmock-actions.h
mbelib/test/gmock/include/gmock/gmock-actions.h