GNU Radio's DSD Package: testing::internal::PredicateFormatterFromMatcher< M > Class Template Reference
testing::internal::PredicateFormatterFromMatcher< M > Class Template Reference
#include <gmock-matchers.h>
Public Member Functions
PredicateFormatterFromMatcher (const M &m)
template<typename T >
AssertionResult operator() (const char *value_text, const T &x) const
PredicateFormatterFromMatcher (const M &m)
template<typename T >
AssertionResult operator() (const char *value_text, const T &x) const
Constructor & Destructor Documentation
PredicateFormatterFromMatcher() [1/2]
template<typename M > testing::internal::PredicateFormatterFromMatcher< M >::PredicateFormatterFromMatcher (const M & m) inline explicit
PredicateFormatterFromMatcher() [2/2]
template<typename M > testing::internal::PredicateFormatterFromMatcher< M >::PredicateFormatterFromMatcher (const M & m) inline explicit
Member Function Documentation
operator()() [1/2]
template<typename M > template<typename T > AssertionResult testing::internal::PredicateFormatterFromMatcher< M >::operator() (const char * value_text, const T & x) const inline
References testing::AssertionFailure(), testing::AssertionSuccess(), testing::internal::MatchPrintAndExplain(), and testing::StringMatchResultListener::str().
operator()() [2/2]
template<typename M > template<typename T > AssertionResult testing::internal::PredicateFormatterFromMatcher< M >::operator() (const char * value_text, const T & x) const inline
References testing::AssertionFailure(), testing::AssertionSuccess(), testing::internal::MatchPrintAndExplain(), and testing::StringMatchResultListener::str().
The documentation for this class was generated from the following files:
dsd/test/gmock/include/gmock/gmock-matchers.h
mbelib/test/gmock/include/gmock/gmock-matchers.h