GNU Radio's DSD Package: testing::internal::UntypedOnCallSpecBase Class Reference
testing::internal::UntypedOnCallSpecBase Class Reference
#include <gmock-spec-builders.h>
Public Member Functions
UntypedOnCallSpecBase (const char *a_file, int a_line)
const char * file () const
int line () const
UntypedOnCallSpecBase (const char *a_file, int a_line)
const char * file () const
int line () const
Protected Types
enum Clause {
kNone , kWith , kWillByDefault , kNone ,
kWith , kWillByDefault
}
enum Clause {
kNone , kWith , kWillByDefault , kNone ,
kWith , kWillByDefault
}
Protected Member Functions
void AssertSpecProperty (bool property, const string &failure_message) const
void ExpectSpecProperty (bool property, const string &failure_message) const
void AssertSpecProperty (bool property, const string &failure_message) const
void ExpectSpecProperty (bool property, const string &failure_message) const
Protected Attributes
const char * file_
int line_
Clause last_clause_
Member Enumeration Documentation
Clause [1/2]
enum testing::internal::UntypedOnCallSpecBase::Clause protected
Enumerator
kNone
kWith
kWillByDefault
kNone
kWith
kWillByDefault
Clause [2/2]
enum testing::internal::UntypedOnCallSpecBase::Clause protected
Enumerator
kNone
kWith
kWillByDefault
kNone
kWith
kWillByDefault
Constructor & Destructor Documentation
UntypedOnCallSpecBase() [1/2]
testing::internal::UntypedOnCallSpecBase::UntypedOnCallSpecBase (const char * a_file, int a_line) inline
UntypedOnCallSpecBase() [2/2]
testing::internal::UntypedOnCallSpecBase::UntypedOnCallSpecBase (const char * a_file, int a_line) inline
Member Function Documentation
AssertSpecProperty() [1/2]
void testing::internal::UntypedOnCallSpecBase::AssertSpecProperty (bool property, const string & failure_message) const inline protected
References testing::internal::Assert().
AssertSpecProperty() [2/2]
void testing::internal::UntypedOnCallSpecBase::AssertSpecProperty (bool property, const string & failure_message) const inline protected
References testing::internal::Assert().
ExpectSpecProperty() [1/2]
void testing::internal::UntypedOnCallSpecBase::ExpectSpecProperty (bool property, const string & failure_message) const inline protected
References testing::internal::Expect().
ExpectSpecProperty() [2/2]
void testing::internal::UntypedOnCallSpecBase::ExpectSpecProperty (bool property, const string & failure_message) const inline protected
References testing::internal::Expect().
file() [1/2]
const char * testing::internal::UntypedOnCallSpecBase::file () const inline
file() [2/2]
const char * testing::internal::UntypedOnCallSpecBase::file () const inline
line() [1/2]
int testing::internal::UntypedOnCallSpecBase::line () const inline
line() [2/2]
int testing::internal::UntypedOnCallSpecBase::line () const inline
Member Data Documentation
file_
const char * testing::internal::UntypedOnCallSpecBase::file_ protected
last_clause_
Clause testing::internal::UntypedOnCallSpecBase::last_clause_ protected
line_
int testing::internal::UntypedOnCallSpecBase::line_ protected
The documentation for this class was generated from the following files:
dsd/test/gmock/include/gmock/gmock-spec-builders.h
mbelib/test/gmock/include/gmock/gmock-spec-builders.h