GNU Radio's DSD Package: testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer > Class Template Reference
testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer > Class Template Reference
#include <gmock-matchers.h>
Classes
class Impl
Public Types
typedef internal::StlContainerView< RhsContainer > RhsView
typedef RhsView::type RhsStlContainer
typedef RhsStlContainer::value_type RhsValue
typedef internal::StlContainerView< RhsContainer > RhsView
typedef RhsView::type RhsStlContainer
typedef RhsStlContainer::value_type RhsValue
Public Member Functions
PointwiseMatcher (const TupleMatcher &tuple_matcher, const RhsContainer &rhs)
template<typename LhsContainer >
operator Matcher< LhsContainer > () const
PointwiseMatcher (const TupleMatcher &tuple_matcher, const RhsContainer &rhs)
template<typename LhsContainer >
operator Matcher< LhsContainer > () const
Member Typedef Documentation
RhsStlContainer [1/2]
template<typename TupleMatcher , typename RhsContainer > typedef RhsView::type testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::RhsStlContainer
RhsStlContainer [2/2]
template<typename TupleMatcher , typename RhsContainer > typedef RhsView::type testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::RhsStlContainer
RhsValue [1/2]
template<typename TupleMatcher , typename RhsContainer > typedef RhsStlContainer::value_type testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::RhsValue
RhsValue [2/2]
template<typename TupleMatcher , typename RhsContainer > typedef RhsStlContainer::value_type testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::RhsValue
RhsView [1/2]
template<typename TupleMatcher , typename RhsContainer > typedef internal::StlContainerView<RhsContainer> testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::RhsView
RhsView [2/2]
template<typename TupleMatcher , typename RhsContainer > typedef internal::StlContainerView<RhsContainer> testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::RhsView
Constructor & Destructor Documentation
PointwiseMatcher() [1/2]
template<typename TupleMatcher , typename RhsContainer > testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::PointwiseMatcher (const TupleMatcher & tuple_matcher, const RhsContainer & rhs) inline
References GTEST_REMOVE_REFERENCE_AND_CONST_, and testing::StaticAssertTypeEq().
PointwiseMatcher() [2/2]
template<typename TupleMatcher , typename RhsContainer > testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::PointwiseMatcher (const TupleMatcher & tuple_matcher, const RhsContainer & rhs) inline
References GTEST_REMOVE_REFERENCE_AND_CONST_, and testing::StaticAssertTypeEq().
Member Function Documentation
operator Matcher< LhsContainer >() [1/2]
template<typename TupleMatcher , typename RhsContainer > template<typename LhsContainer > testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::operator Matcher< LhsContainer > () const inline
References testing::MakeMatcher().
operator Matcher< LhsContainer >() [2/2]
template<typename TupleMatcher , typename RhsContainer > template<typename LhsContainer > testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::operator Matcher< LhsContainer > () const inline
References testing::MakeMatcher().
The documentation for this class was generated from the following files:
dsd/test/gmock/include/gmock/gmock-matchers.h
mbelib/test/gmock/include/gmock/gmock-matchers.h