GNU Radio's DSD Package: descramble.h File Reference
descramble.h File Reference
#include <stdio.h>
#include <string.h>
Functions
int traceBack (int *out, int *m_pathMemory0, int *m_pathMemory1, int *m_pathMemory2, int *m_pathMemory3)
void viterbiDecode (int n, int *data, int *m_pathMemory0, int *m_pathMemory1, int *m_pathMemory2, int *m_pathMemory3, int *m_pathMetric)
int FECdecoder (int *in, int *out)
void deinterleave (int *in, int *out)
void scramble (int *in, int *out)
function scramble
Function Documentation
deinterleave()
void deinterleave (int * in, int * out)
FECdecoder()
int FECdecoder (int * in, int * out)
References traceBack(), and viterbiDecode().
scramble()
void scramble (int * in, int * out)
function scramble
traceBack()
int traceBack (int * out, int * m_pathMemory0, int * m_pathMemory1, int * m_pathMemory2, int * m_pathMemory3)
Referenced by FECdecoder().
viterbiDecode()
void viterbiDecode (int n, int * data, int * m_pathMemory0, int * m_pathMemory1, int * m_pathMemory2, int * m_pathMemory3, int * m_pathMetric)
Referenced by FECdecoder().