GNU Radio's DSD Package: testing Namespace Reference
testing Namespace Reference
Namespaces
namespace internal
namespace internal2
Classes
class Action
class ActionInterface
class AssertionResult
class Cardinality
class CardinalityInterface
class DefaultValue
class DefaultValue< T & >
class DefaultValue< void >
class EmptyTestEventListener
class Environment
class Expectation
class ExpectationSet
class InSequence
class Matcher
class Matcher< const internal::string & >
class Matcher< internal::string >
class MatcherDescriberInterface
class MatcherInterface
class MatchResultListener
class Message
class Mock
class MockFunction
class MockFunction< R(A0)>
class MockFunction< R(A0, A1)>
class MockFunction< R(A0, A1, A2)>
class MockFunction< R(A0, A1, A2, A3)>
class MockFunction< R(A0, A1, A2, A3, A4)>
class MockFunction< R(A0, A1, A2, A3, A4, A5)>
class MockFunction< R(A0, A1, A2, A3, A4, A5, A6)>
class MockFunction< R(A0, A1, A2, A3, A4, A5, A6, A7)>
class MockFunction< R(A0, A1, A2, A3, A4, A5, A6, A7, A8)>
class MockFunction< R(A0, A1, A2, A3, A4, A5, A6, A7, A8, A9)>
class NaggyMock
class NiceMock
class PolymorphicAction
class PolymorphicMatcher
class SafeMatcherCastImpl
class ScopedFakeTestPartResultReporter
class Sequence
class StrictMock
class StringMatchResultListener
class Test
class TestCase
class TestEventListener
class TestEventListeners
class TestInfo
class TestPartResult
class TestPartResultArray
class TestPartResultReporterInterface
class TestProperty
class TestResult
class UnitTest
Typedefs
typedef internal::IgnoredValue Unused
typedef internal::TimeInMillis TimeInMillis
Functions
template<typename F >
Action< F > MakeAction (ActionInterface< F > *impl)
template<typename Impl >
PolymorphicAction< Impl > MakePolymorphicAction (const Impl &impl)
template<typename R >
internal::ReturnAction< R > Return (R value)
PolymorphicAction< internal::ReturnNullAction > ReturnNull ()
PolymorphicAction< internal::ReturnVoidAction > Return ()
template<typename R >
internal::ReturnRefAction< R > ReturnRef (R &x)
template<typename R >
internal::ReturnRefOfCopyAction< R > ReturnRefOfCopy (const R &x)
internal::DoDefaultAction DoDefault ()
template<size_t N, typename T >
PolymorphicAction< internal::SetArgumentPointeeAction< N, T, internal::IsAProtocolMessage< T >::value > > SetArgPointee (const T &x)
template<size_t N>
PolymorphicAction< internal::SetArgumentPointeeAction< N, const char *, false > > SetArgPointee (const char *p)
template<size_t N>
PolymorphicAction< internal::SetArgumentPointeeAction< N, const wchar_t *, false > > SetArgPointee (const wchar_t *p)
template<size_t N, typename T >
PolymorphicAction< internal::SetArgumentPointeeAction< N, T, internal::IsAProtocolMessage< T >::value > > SetArgumentPointee (const T &x)
template<typename T1 , typename T2 >
PolymorphicAction< internal::AssignAction< T1, T2 > > Assign (T1 *ptr, T2 val)
template<typename T >
PolymorphicAction< internal::SetErrnoAndReturnAction< T > > SetErrnoAndReturn (int errval, T result)
template<typename FunctionImpl >
PolymorphicAction< internal::InvokeWithoutArgsAction< FunctionImpl > > InvokeWithoutArgs (FunctionImpl function_impl)
template<class Class , typename MethodPtr >
PolymorphicAction< internal::InvokeMethodWithoutArgsAction< Class, MethodPtr > > InvokeWithoutArgs (Class *obj_ptr, MethodPtr method_ptr)
template<typename A >
internal::IgnoreResultAction< A > IgnoreResult (const A &an_action)
template<typename T >
internal::ReferenceWrapper< T > ByRef (T &l_value)
GTEST_API_ Cardinality AtLeast (int n)
GTEST_API_ Cardinality AtMost (int n)
GTEST_API_ Cardinality AnyNumber ()
GTEST_API_ Cardinality Between (int min, int max)
GTEST_API_ Cardinality Exactly (int n)
Cardinality MakeCardinality (const CardinalityInterface *c)
template<int k1, typename InnerAction >
internal::WithArgsAction< InnerAction, k1 > WithArgs (const InnerAction &action)
template<int k1, int k2, typename InnerAction >
internal::WithArgsAction< InnerAction, k1, k2 > WithArgs (const InnerAction &action)
template<int k1, int k2, int k3, typename InnerAction >
internal::WithArgsAction< InnerAction, k1, k2, k3 > WithArgs (const InnerAction &action)
template<int k1, int k2, int k3, int k4, typename InnerAction >
internal::WithArgsAction< InnerAction, k1, k2, k3, k4 > WithArgs (const InnerAction &action)
template<int k1, int k2, int k3, int k4, int k5, typename InnerAction >
internal::WithArgsAction< InnerAction, k1, k2, k3, k4, k5 > WithArgs (const InnerAction &action)
template<int k1, int k2, int k3, int k4, int k5, int k6, typename InnerAction >
internal::WithArgsAction< InnerAction, k1, k2, k3, k4, k5, k6 > WithArgs (const InnerAction &action)
template<int k1, int k2, int k3, int k4, int k5, int k6, int k7, typename InnerAction >
internal::WithArgsAction< InnerAction, k1, k2, k3, k4, k5, k6, k7 > WithArgs (const InnerAction &action)
template<int k1, int k2, int k3, int k4, int k5, int k6, int k7, int k8, typename InnerAction >
internal::WithArgsAction< InnerAction, k1, k2, k3, k4, k5, k6, k7, k8 > WithArgs (const InnerAction &action)
template<int k1, int k2, int k3, int k4, int k5, int k6, int k7, int k8, int k9, typename InnerAction >
internal::WithArgsAction< InnerAction, k1, k2, k3, k4, k5, k6, k7, k8, k9 > WithArgs (const InnerAction &action)
template<int k1, int k2, int k3, int k4, int k5, int k6, int k7, int k8, int k9, int k10, typename InnerAction >
internal::WithArgsAction< InnerAction, k1, k2, k3, k4, k5, k6, k7, k8, k9, k10 > WithArgs (const InnerAction &action)
template<typename Action1 , typename Action2 >
internal::DoBothAction< Action1, Action2 > DoAll (Action1 a1, Action2 a2)
template<typename Action1 , typename Action2 , typename Action3 >
internal::DoBothAction< Action1, internal::DoBothAction< Action2, Action3 > > DoAll (Action1 a1, Action2 a2, Action3 a3)
template<typename Action1 , typename Action2 , typename Action3 , typename Action4 >
internal::DoBothAction< Action1, internal::DoBothAction< Action2, internal::DoBothAction< Action3, Action4 > > > DoAll (Action1 a1, Action2 a2, Action3 a3, Action4 a4)
template<typename Action1 , typename Action2 , typename Action3 , typename Action4 , typename Action5 >
internal::DoBothAction< Action1, internal::DoBothAction< Action2, internal::DoBothAction< Action3, internal::DoBothAction< Action4, Action5 > > > > DoAll (Action1 a1, Action2 a2, Action3 a3, Action4 a4, Action5 a5)
template<typename Action1 , typename Action2 , typename Action3 , typename Action4 , typename Action5 , typename Action6 >
internal::DoBothAction< Action1, internal::DoBothAction< Action2, internal::DoBothAction< Action3, internal::DoBothAction< Action4, internal::DoBothAction< Action5, Action6 > > > > > DoAll (Action1 a1, Action2 a2, Action3 a3, Action4 a4, Action5 a5, Action6 a6)
template<typename Action1 , typename Action2 , typename Action3 , typename Action4 , typename Action5 , typename Action6 , typename Action7 >
internal::DoBothAction< Action1, internal::DoBothAction< Action2, internal::DoBothAction< Action3, internal::DoBothAction< Action4, internal::DoBothAction< Action5, internal::DoBothAction< Action6, Action7 > > > > > > DoAll (Action1 a1, Action2 a2, Action3 a3, Action4 a4, Action5 a5, Action6 a6, Action7 a7)
template<typename Action1 , typename Action2 , typename Action3 , typename Action4 , typename Action5 , typename Action6 , typename Action7 , typename Action8 >
internal::DoBothAction< Action1, internal::DoBothAction< Action2, internal::DoBothAction< Action3, internal::DoBothAction< Action4, internal::DoBothAction< Action5, internal::DoBothAction< Action6, internal::DoBothAction< Action7, Action8 > > > > > > > DoAll (Action1 a1, Action2 a2, Action3 a3, Action4 a4, Action5 a5, Action6 a6, Action7 a7, Action8 a8)
template<typename Action1 , typename Action2 , typename Action3 , typename Action4 , typename Action5 , typename Action6 , typename Action7 , typename Action8 , typename Action9 >
internal::DoBothAction< Action1, internal::DoBothAction< Action2, internal::DoBothAction< Action3, internal::DoBothAction< Action4, internal::DoBothAction< Action5, internal::DoBothAction< Action6, internal::DoBothAction< Action7, internal::DoBothAction< Action8, Action9 > > > > > > > > DoAll (Action1 a1, Action2 a2, Action3 a3, Action4 a4, Action5 a5, Action6 a6, Action7 a7, Action8 a8, Action9 a9)
template<typename Action1 , typename Action2 , typename Action3 , typename Action4 , typename Action5 , typename Action6 , typename Action7 , typename Action8 , typename Action9 , typename Action10 >
internal::DoBothAction< Action1, internal::DoBothAction< Action2, internal::DoBothAction< Action3, internal::DoBothAction< Action4, internal::DoBothAction< Action5, internal::DoBothAction< Action6, internal::DoBothAction< Action7, internal::DoBothAction< Action8, internal::DoBothAction< Action9, Action10 > > > > > > > > > DoAll (Action1 a1, Action2 a2, Action3 a3, Action4 a4, Action5 a5, Action6 a6, Action7 a7, Action8 a8, Action9 a9, Action10 a10)
ACTION_TEMPLATE (InvokeArgument, HAS_1_TEMPLATE_PARAMS(int, k), AND_0_VALUE_PARAMS())
ACTION_TEMPLATE (InvokeArgument, HAS_1_TEMPLATE_PARAMS(int, k), AND_1_VALUE_PARAMS(p0))
ACTION_TEMPLATE (InvokeArgument, HAS_1_TEMPLATE_PARAMS(int, k), AND_2_VALUE_PARAMS(p0, p1))
ACTION_TEMPLATE (InvokeArgument, HAS_1_TEMPLATE_PARAMS(int, k), AND_3_VALUE_PARAMS(p0, p1, p2))
ACTION_TEMPLATE (InvokeArgument, HAS_1_TEMPLATE_PARAMS(int, k), AND_4_VALUE_PARAMS(p0, p1, p2, p3))
ACTION_TEMPLATE (InvokeArgument, HAS_1_TEMPLATE_PARAMS(int, k), AND_5_VALUE_PARAMS(p0, p1, p2, p3, p4))
ACTION_TEMPLATE (InvokeArgument, HAS_1_TEMPLATE_PARAMS(int, k), AND_6_VALUE_PARAMS(p0, p1, p2, p3, p4, p5))
ACTION_TEMPLATE (InvokeArgument, HAS_1_TEMPLATE_PARAMS(int, k), AND_7_VALUE_PARAMS(p0, p1, p2, p3, p4, p5, p6))
ACTION_TEMPLATE (InvokeArgument, HAS_1_TEMPLATE_PARAMS(int, k), AND_8_VALUE_PARAMS(p0, p1, p2, p3, p4, p5, p6, p7))
ACTION_TEMPLATE (InvokeArgument, HAS_1_TEMPLATE_PARAMS(int, k), AND_9_VALUE_PARAMS(p0, p1, p2, p3, p4, p5, p6, p7, p8))
ACTION_TEMPLATE (InvokeArgument, HAS_1_TEMPLATE_PARAMS(int, k), AND_10_VALUE_PARAMS(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9))
ACTION_TEMPLATE (ReturnNew, HAS_1_TEMPLATE_PARAMS(typename, T), AND_0_VALUE_PARAMS())
ACTION_TEMPLATE (ReturnNew, HAS_1_TEMPLATE_PARAMS(typename, T), AND_1_VALUE_PARAMS(p0))
ACTION_TEMPLATE (ReturnNew, HAS_1_TEMPLATE_PARAMS(typename, T), AND_2_VALUE_PARAMS(p0, p1))
ACTION_TEMPLATE (ReturnNew, HAS_1_TEMPLATE_PARAMS(typename, T), AND_3_VALUE_PARAMS(p0, p1, p2))
ACTION_TEMPLATE (ReturnNew, HAS_1_TEMPLATE_PARAMS(typename, T), AND_4_VALUE_PARAMS(p0, p1, p2, p3))
ACTION_TEMPLATE (ReturnNew, HAS_1_TEMPLATE_PARAMS(typename, T), AND_5_VALUE_PARAMS(p0, p1, p2, p3, p4))
ACTION_TEMPLATE (ReturnNew, HAS_1_TEMPLATE_PARAMS(typename, T), AND_6_VALUE_PARAMS(p0, p1, p2, p3, p4, p5))
ACTION_TEMPLATE (ReturnNew, HAS_1_TEMPLATE_PARAMS(typename, T), AND_7_VALUE_PARAMS(p0, p1, p2, p3, p4, p5, p6))
ACTION_TEMPLATE (ReturnNew, HAS_1_TEMPLATE_PARAMS(typename, T), AND_8_VALUE_PARAMS(p0, p1, p2, p3, p4, p5, p6, p7))
ACTION_TEMPLATE (ReturnNew, HAS_1_TEMPLATE_PARAMS(typename, T), AND_9_VALUE_PARAMS(p0, p1, p2, p3, p4, p5, p6, p7, p8))
ACTION_TEMPLATE (ReturnNew, HAS_1_TEMPLATE_PARAMS(typename, T), AND_10_VALUE_PARAMS(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9))
template<typename InnerMatcher >
internal::ArgsMatcher< InnerMatcher > Args (const InnerMatcher &matcher)
template<int k1, typename InnerMatcher >
internal::ArgsMatcher< InnerMatcher, k1 > Args (const InnerMatcher &matcher)
template<int k1, int k2, typename InnerMatcher >
internal::ArgsMatcher< InnerMatcher, k1, k2 > Args (const InnerMatcher &matcher)
template<int k1, int k2, int k3, typename InnerMatcher >
internal::ArgsMatcher< InnerMatcher, k1, k2, k3 > Args (const InnerMatcher &matcher)
template<int k1, int k2, int k3, int k4, typename InnerMatcher >
internal::ArgsMatcher< InnerMatcher, k1, k2, k3, k4 > Args (const InnerMatcher &matcher)
template<int k1, int k2, int k3, int k4, int k5, typename InnerMatcher >
internal::ArgsMatcher< InnerMatcher, k1, k2, k3, k4, k5 > Args (const InnerMatcher &matcher)
template<int k1, int k2, int k3, int k4, int k5, int k6, typename InnerMatcher >
internal::ArgsMatcher< InnerMatcher, k1, k2, k3, k4, k5, k6 > Args (const InnerMatcher &matcher)
template<int k1, int k2, int k3, int k4, int k5, int k6, int k7, typename InnerMatcher >
internal::ArgsMatcher< InnerMatcher, k1, k2, k3, k4, k5, k6, k7 > Args (const InnerMatcher &matcher)
template<int k1, int k2, int k3, int k4, int k5, int k6, int k7, int k8, typename InnerMatcher >
internal::ArgsMatcher< InnerMatcher, k1, k2, k3, k4, k5, k6, k7, k8 > Args (const InnerMatcher &matcher)
template<int k1, int k2, int k3, int k4, int k5, int k6, int k7, int k8, int k9, typename InnerMatcher >
internal::ArgsMatcher< InnerMatcher, k1, k2, k3, k4, k5, k6, k7, k8, k9 > Args (const InnerMatcher &matcher)
template<int k1, int k2, int k3, int k4, int k5, int k6, int k7, int k8, int k9, int k10, typename InnerMatcher >
internal::ArgsMatcher< InnerMatcher, k1, k2, k3, k4, k5, k6, k7, k8, k9, k10 > Args (const InnerMatcher &matcher)
internal::ElementsAreMatcher< std::tr1::tuple<> > ElementsAre ()
template<typename T1 >
internal::ElementsAreMatcher< std::tr1::tuple< typename internal::DecayArray< T1 >::type > > ElementsAre (const T1 &e1)
template<typename T1 , typename T2 >
internal::ElementsAreMatcher< std::tr1::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type > > ElementsAre (const T1 &e1, const T2 &e2)
template<typename T1 , typename T2 , typename T3 >
internal::ElementsAreMatcher< std::tr1::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type > > ElementsAre (const T1 &e1, const T2 &e2, const T3 &e3)
template<typename T1 , typename T2 , typename T3 , typename T4 >
internal::ElementsAreMatcher< std::tr1::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type > > ElementsAre (const T1 &e1, const T2 &e2, const T3 &e3, const T4 &e4)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 >
internal::ElementsAreMatcher< std::tr1::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type, typename internal::DecayArray< T5 >::type > > ElementsAre (const T1 &e1, const T2 &e2, const T3 &e3, const T4 &e4, const T5 &e5)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 >
internal::ElementsAreMatcher< std::tr1::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type, typename internal::DecayArray< T5 >::type, typename internal::DecayArray< T6 >::type > > ElementsAre (const T1 &e1, const T2 &e2, const T3 &e3, const T4 &e4, const T5 &e5, const T6 &e6)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 >
internal::ElementsAreMatcher< std::tr1::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type, typename internal::DecayArray< T5 >::type, typename internal::DecayArray< T6 >::type, typename internal::DecayArray< T7 >::type > > ElementsAre (const T1 &e1, const T2 &e2, const T3 &e3, const T4 &e4, const T5 &e5, const T6 &e6, const T7 &e7)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 >
internal::ElementsAreMatcher< std::tr1::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type, typename internal::DecayArray< T5 >::type, typename internal::DecayArray< T6 >::type, typename internal::DecayArray< T7 >::type, typename internal::DecayArray< T8 >::type > > ElementsAre (const T1 &e1, const T2 &e2, const T3 &e3, const T4 &e4, const T5 &e5, const T6 &e6, const T7 &e7, const T8 &e8)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 >
internal::ElementsAreMatcher< std::tr1::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type, typename internal::DecayArray< T5 >::type, typename internal::DecayArray< T6 >::type, typename internal::DecayArray< T7 >::type, typename internal::DecayArray< T8 >::type, typename internal::DecayArray< T9 >::type > > ElementsAre (const T1 &e1, const T2 &e2, const T3 &e3, const T4 &e4, const T5 &e5, const T6 &e6, const T7 &e7, const T8 &e8, const T9 &e9)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 >
internal::ElementsAreMatcher< std::tr1::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type, typename internal::DecayArray< T5 >::type, typename internal::DecayArray< T6 >::type, typename internal::DecayArray< T7 >::type, typename internal::DecayArray< T8 >::type, typename internal::DecayArray< T9 >::type, typename internal::DecayArray< T10 >::type > > ElementsAre (const T1 &e1, const T2 &e2, const T3 &e3, const T4 &e4, const T5 &e5, const T6 &e6, const T7 &e7, const T8 &e8, const T9 &e9, const T10 &e10)
internal::UnorderedElementsAreMatcher< std::tr1::tuple<> > UnorderedElementsAre ()
template<typename T1 >
internal::UnorderedElementsAreMatcher< std::tr1::tuple< typename internal::DecayArray< T1 >::type > > UnorderedElementsAre (const T1 &e1)
template<typename T1 , typename T2 >
internal::UnorderedElementsAreMatcher< std::tr1::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type > > UnorderedElementsAre (const T1 &e1, const T2 &e2)
template<typename T1 , typename T2 , typename T3 >
internal::UnorderedElementsAreMatcher< std::tr1::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type > > UnorderedElementsAre (const T1 &e1, const T2 &e2, const T3 &e3)
template<typename T1 , typename T2 , typename T3 , typename T4 >
internal::UnorderedElementsAreMatcher< std::tr1::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type > > UnorderedElementsAre (const T1 &e1, const T2 &e2, const T3 &e3, const T4 &e4)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 >
internal::UnorderedElementsAreMatcher< std::tr1::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type, typename internal::DecayArray< T5 >::type > > UnorderedElementsAre (const T1 &e1, const T2 &e2, const T3 &e3, const T4 &e4, const T5 &e5)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 >
internal::UnorderedElementsAreMatcher< std::tr1::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type, typename internal::DecayArray< T5 >::type, typename internal::DecayArray< T6 >::type > > UnorderedElementsAre (const T1 &e1, const T2 &e2, const T3 &e3, const T4 &e4, const T5 &e5, const T6 &e6)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 >
internal::UnorderedElementsAreMatcher< std::tr1::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type, typename internal::DecayArray< T5 >::type, typename internal::DecayArray< T6 >::type, typename internal::DecayArray< T7 >::type > > UnorderedElementsAre (const T1 &e1, const T2 &e2, const T3 &e3, const T4 &e4, const T5 &e5, const T6 &e6, const T7 &e7)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 >
internal::UnorderedElementsAreMatcher< std::tr1::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type, typename internal::DecayArray< T5 >::type, typename internal::DecayArray< T6 >::type, typename internal::DecayArray< T7 >::type, typename internal::DecayArray< T8 >::type > > UnorderedElementsAre (const T1 &e1, const T2 &e2, const T3 &e3, const T4 &e4, const T5 &e5, const T6 &e6, const T7 &e7, const T8 &e8)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 >
internal::UnorderedElementsAreMatcher< std::tr1::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type, typename internal::DecayArray< T5 >::type, typename internal::DecayArray< T6 >::type, typename internal::DecayArray< T7 >::type, typename internal::DecayArray< T8 >::type, typename internal::DecayArray< T9 >::type > > UnorderedElementsAre (const T1 &e1, const T2 &e2, const T3 &e3, const T4 &e4, const T5 &e5, const T6 &e6, const T7 &e7, const T8 &e8, const T9 &e9)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 >
internal::UnorderedElementsAreMatcher< std::tr1::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type, typename internal::DecayArray< T5 >::type, typename internal::DecayArray< T6 >::type, typename internal::DecayArray< T7 >::type, typename internal::DecayArray< T8 >::type, typename internal::DecayArray< T9 >::type, typename internal::DecayArray< T10 >::type > > UnorderedElementsAre (const T1 &e1, const T2 &e2, const T3 &e3, const T4 &e4, const T5 &e5, const T6 &e6, const T7 &e7, const T8 &e8, const T9 &e9, const T10 &e10)
template<typename M1 , typename M2 >
internal::AllOfResult2< M1, M2 >::type AllOf (M1 m1, M2 m2)
template<typename M1 , typename M2 , typename M3 >
internal::AllOfResult3< M1, M2, M3 >::type AllOf (M1 m1, M2 m2, M3 m3)
template<typename M1 , typename M2 , typename M3 , typename M4 >
internal::AllOfResult4< M1, M2, M3, M4 >::type AllOf (M1 m1, M2 m2, M3 m3, M4 m4)
template<typename M1 , typename M2 , typename M3 , typename M4 , typename M5 >
internal::AllOfResult5< M1, M2, M3, M4, M5 >::type AllOf (M1 m1, M2 m2, M3 m3, M4 m4, M5 m5)
template<typename M1 , typename M2 , typename M3 , typename M4 , typename M5 , typename M6 >
internal::AllOfResult6< M1, M2, M3, M4, M5, M6 >::type AllOf (M1 m1, M2 m2, M3 m3, M4 m4, M5 m5, M6 m6)
template<typename M1 , typename M2 , typename M3 , typename M4 , typename M5 , typename M6 , typename M7 >
internal::AllOfResult7< M1, M2, M3, M4, M5, M6, M7 >::type AllOf (M1 m1, M2 m2, M3 m3, M4 m4, M5 m5, M6 m6, M7 m7)
template<typename M1 , typename M2 , typename M3 , typename M4 , typename M5 , typename M6 , typename M7 , typename M8 >
internal::AllOfResult8< M1, M2, M3, M4, M5, M6, M7, M8 >::type AllOf (M1 m1, M2 m2, M3 m3, M4 m4, M5 m5, M6 m6, M7 m7, M8 m8)
template<typename M1 , typename M2 , typename M3 , typename M4 , typename M5 , typename M6 , typename M7 , typename M8 , typename M9 >
internal::AllOfResult9< M1, M2, M3, M4, M5, M6, M7, M8, M9 >::type AllOf (M1 m1, M2 m2, M3 m3, M4 m4, M5 m5, M6 m6, M7 m7, M8 m8, M9 m9)
template<typename M1 , typename M2 , typename M3 , typename M4 , typename M5 , typename M6 , typename M7 , typename M8 , typename M9 , typename M10 >
internal::AllOfResult10< M1, M2, M3, M4, M5, M6, M7, M8, M9, M10 >::type AllOf (M1 m1, M2 m2, M3 m3, M4 m4, M5 m5, M6 m6, M7 m7, M8 m8, M9 m9, M10 m10)
template<typename M1 , typename M2 >
internal::AnyOfResult2< M1, M2 >::type AnyOf (M1 m1, M2 m2)
template<typename M1 , typename M2 , typename M3 >
internal::AnyOfResult3< M1, M2, M3 >::type AnyOf (M1 m1, M2 m2, M3 m3)
template<typename M1 , typename M2 , typename M3 , typename M4 >
internal::AnyOfResult4< M1, M2, M3, M4 >::type AnyOf (M1 m1, M2 m2, M3 m3, M4 m4)
template<typename M1 , typename M2 , typename M3 , typename M4 , typename M5 >
internal::AnyOfResult5< M1, M2, M3, M4, M5 >::type AnyOf (M1 m1, M2 m2, M3 m3, M4 m4, M5 m5)
template<typename M1 , typename M2 , typename M3 , typename M4 , typename M5 , typename M6 >
internal::AnyOfResult6< M1, M2, M3, M4, M5, M6 >::type AnyOf (M1 m1, M2 m2, M3 m3, M4 m4, M5 m5, M6 m6)
template<typename M1 , typename M2 , typename M3 , typename M4 , typename M5 , typename M6 , typename M7 >
internal::AnyOfResult7< M1, M2, M3, M4, M5, M6, M7 >::type AnyOf (M1 m1, M2 m2, M3 m3, M4 m4, M5 m5, M6 m6, M7 m7)
template<typename M1 , typename M2 , typename M3 , typename M4 , typename M5 , typename M6 , typename M7 , typename M8 >
internal::AnyOfResult8< M1, M2, M3, M4, M5, M6, M7, M8 >::type AnyOf (M1 m1, M2 m2, M3 m3, M4 m4, M5 m5, M6 m6, M7 m7, M8 m8)
template<typename M1 , typename M2 , typename M3 , typename M4 , typename M5 , typename M6 , typename M7 , typename M8 , typename M9 >
internal::AnyOfResult9< M1, M2, M3, M4, M5, M6, M7, M8, M9 >::type AnyOf (M1 m1, M2 m2, M3 m3, M4 m4, M5 m5, M6 m6, M7 m7, M8 m8, M9 m9)
template<typename M1 , typename M2 , typename M3 , typename M4 , typename M5 , typename M6 , typename M7 , typename M8 , typename M9 , typename M10 >
internal::AnyOfResult10< M1, M2, M3, M4, M5, M6, M7, M8, M9, M10 >::type AnyOf (M1 m1, M2 m2, M3 m3, M4 m4, M5 m5, M6 m6, M7 m7, M8 m8, M9 m9, M10 m10)
template<typename T >
Matcher< T > MakeMatcher (const MatcherInterface< T > *impl)
template<class Impl >
PolymorphicMatcher< Impl > MakePolymorphicMatcher (const Impl &impl)
template<typename T , typename M >
Matcher< T > MatcherCast (M matcher)
template<typename T , typename M >
Matcher< T > SafeMatcherCast (const M &polymorphic_matcher)
template<typename T >
Matcher< T > A ()
template<typename Iter >
internal::ElementsAreArrayMatcher< typename ::std::iterator_traits< Iter >::value_type > ElementsAreArray (Iter first, Iter last)
template<typename T >
internal::ElementsAreArrayMatcher< T > ElementsAreArray (const T *pointer, size_t count)
template<typename T , size_t N>
internal::ElementsAreArrayMatcher< T > ElementsAreArray (const T(&array)[N])
template<typename T , typename A >
internal::ElementsAreArrayMatcher< T > ElementsAreArray (const ::std::vector< T, A > &vec)
template<typename Iter >
internal::UnorderedElementsAreArrayMatcher< typename ::std::iterator_traits< Iter >::value_type > UnorderedElementsAreArray (Iter first, Iter last)
template<typename T >
internal::UnorderedElementsAreArrayMatcher< T > UnorderedElementsAreArray (const T *pointer, size_t count)
template<typename T , size_t N>
internal::UnorderedElementsAreArrayMatcher< T > UnorderedElementsAreArray (const T(&array)[N])
template<typename T , typename A >
internal::UnorderedElementsAreArrayMatcher< T > UnorderedElementsAreArray (const ::std::vector< T, A > &vec)
template<typename T >
Matcher< T > An ()
template<typename T >
internal::EqMatcher< T > Eq (T x)
template<typename Lhs , typename Rhs >
Matcher< Lhs > TypedEq (const Rhs &rhs)
template<typename Rhs >
internal::GeMatcher< Rhs > Ge (Rhs x)
template<typename Rhs >
internal::GtMatcher< Rhs > Gt (Rhs x)
template<typename Rhs >
internal::LeMatcher< Rhs > Le (Rhs x)
template<typename Rhs >
internal::LtMatcher< Rhs > Lt (Rhs x)
template<typename Rhs >
internal::NeMatcher< Rhs > Ne (Rhs x)
PolymorphicMatcher< internal::IsNullMatcher > IsNull ()
PolymorphicMatcher< internal::NotNullMatcher > NotNull ()
template<typename T >
internal::RefMatcher< T & > Ref (T &x)
internal::FloatingEqMatcher< double > DoubleEq (double rhs)
internal::FloatingEqMatcher< double > NanSensitiveDoubleEq (double rhs)
internal::FloatingEqMatcher< double > DoubleNear (double rhs, double max_abs_error)
internal::FloatingEqMatcher< double > NanSensitiveDoubleNear (double rhs, double max_abs_error)
internal::FloatingEqMatcher< float > FloatEq (float rhs)
internal::FloatingEqMatcher< float > NanSensitiveFloatEq (float rhs)
internal::FloatingEqMatcher< float > FloatNear (float rhs, float max_abs_error)
internal::FloatingEqMatcher< float > NanSensitiveFloatNear (float rhs, float max_abs_error)
template<typename InnerMatcher >
internal::PointeeMatcher< InnerMatcher > Pointee (const InnerMatcher &inner_matcher)
template<typename Class , typename FieldType , typename FieldMatcher >
PolymorphicMatcher< internal::FieldMatcher< Class, FieldType > > Field (FieldType Class::*field, const FieldMatcher &matcher)
template<typename Class , typename PropertyType , typename PropertyMatcher >
PolymorphicMatcher< internal::PropertyMatcher< Class, PropertyType > > Property (PropertyType(Class::*property)() const, const PropertyMatcher &matcher)
template<typename Callable , typename ResultOfMatcher >
internal::ResultOfMatcher< Callable > ResultOf (Callable callable, const ResultOfMatcher &matcher)
PolymorphicMatcher< internal::StrEqualityMatcher< internal::string > > StrEq (const internal::string &str)
PolymorphicMatcher< internal::StrEqualityMatcher< internal::string > > StrNe (const internal::string &str)
PolymorphicMatcher< internal::StrEqualityMatcher< internal::string > > StrCaseEq (const internal::string &str)
PolymorphicMatcher< internal::StrEqualityMatcher< internal::string > > StrCaseNe (const internal::string &str)
PolymorphicMatcher< internal::HasSubstrMatcher< internal::string > > HasSubstr (const internal::string &substring)
PolymorphicMatcher< internal::StartsWithMatcher< internal::string > > StartsWith (const internal::string &prefix)
PolymorphicMatcher< internal::EndsWithMatcher< internal::string > > EndsWith (const internal::string &suffix)
PolymorphicMatcher< internal::MatchesRegexMatcher > MatchesRegex (const internal::RE *regex)
PolymorphicMatcher< internal::MatchesRegexMatcher > MatchesRegex (const internal::string &regex)
PolymorphicMatcher< internal::MatchesRegexMatcher > ContainsRegex (const internal::RE *regex)
PolymorphicMatcher< internal::MatchesRegexMatcher > ContainsRegex (const internal::string &regex)
internal::Eq2Matcher Eq ()
internal::Ge2Matcher Ge ()
internal::Gt2Matcher Gt ()
internal::Le2Matcher Le ()
internal::Lt2Matcher Lt ()
internal::Ne2Matcher Ne ()
template<typename InnerMatcher >
internal::NotMatcher< InnerMatcher > Not (InnerMatcher m)
template<typename Predicate >
PolymorphicMatcher< internal::TrulyMatcher< Predicate > > Truly (Predicate pred)
template<typename SizeMatcher >
internal::SizeIsMatcher< SizeMatcher > SizeIs (const SizeMatcher &size_matcher)
template<typename Container >
PolymorphicMatcher< internal::ContainerEqMatcher< GTEST_REMOVE_CONST_(Container)> > ContainerEq (const Container &rhs)
template<typename Comparator , typename ContainerMatcher >
internal::WhenSortedByMatcher< Comparator, ContainerMatcher > WhenSortedBy (const Comparator &comparator, const ContainerMatcher &container_matcher)
template<typename ContainerMatcher >
internal::WhenSortedByMatcher< internal::LessComparator, ContainerMatcher > WhenSorted (const ContainerMatcher &container_matcher)
template<typename TupleMatcher , typename Container >
internal::PointwiseMatcher< TupleMatcher, GTEST_REMOVE_CONST_(Container)> Pointwise (const TupleMatcher &tuple_matcher, const Container &rhs)
template<typename M >
internal::ContainsMatcher< M > Contains (M matcher)
template<typename M >
internal::EachMatcher< M > Each (M matcher)
template<typename M >
internal::KeyMatcher< M > Key (M inner_matcher)
template<typename FirstMatcher , typename SecondMatcher >
internal::PairMatcher< FirstMatcher, SecondMatcher > Pair (FirstMatcher first_matcher, SecondMatcher second_matcher)
template<typename M >
internal::MatcherAsPredicate< M > Matches (M matcher)
template<typename T , typename M >
bool Value (const T &value, M matcher)
template<typename T , typename M >
bool ExplainMatchResult (M matcher, const T &value, MatchResultListener *listener)
template<typename InnerMatcher >
InnerMatcher AllArgs (const InnerMatcher &matcher)
template<typename FunctionImpl >
PolymorphicAction< internal::InvokeAction< FunctionImpl > > Invoke (FunctionImpl function_impl)
template<class Class , typename MethodPtr >
PolymorphicAction< internal::InvokeMethodAction< Class, MethodPtr > > Invoke (Class *obj_ptr, MethodPtr method_ptr)
template<typename InnerAction >
internal::WithArgsAction< InnerAction > WithoutArgs (const InnerAction &action)
template<int k, typename InnerAction >
internal::WithArgsAction< InnerAction, k > WithArg (const InnerAction &action)
ACTION_TEMPLATE (ReturnArg, HAS_1_TEMPLATE_PARAMS(int, k), AND_0_VALUE_PARAMS())
ACTION_TEMPLATE (SaveArg, HAS_1_TEMPLATE_PARAMS(int, k), AND_1_VALUE_PARAMS(pointer))
ACTION_TEMPLATE (SaveArgPointee, HAS_1_TEMPLATE_PARAMS(int, k), AND_1_VALUE_PARAMS(pointer))
ACTION_TEMPLATE (SetArgReferee, HAS_1_TEMPLATE_PARAMS(int, k), AND_1_VALUE_PARAMS(value))
ACTION_TEMPLATE (SetArrayArgument, HAS_1_TEMPLATE_PARAMS(int, k), AND_2_VALUE_PARAMS(first, last))
ACTION_TEMPLATE (DeleteArg, HAS_1_TEMPLATE_PARAMS(int, k), AND_0_VALUE_PARAMS())
ACTION_P (ReturnPointee, pointer)
MATCHER (IsEmpty, negation ? "isn't empty" :"is empty")
template<typename T >
const T & Const (const T &x)
GMOCK_DECLARE_bool_ (catch_leaked_mocks)
GMOCK_DECLARE_string_ (verbose)
GTEST_API_ void InitGoogleMock (int *argc, char **argv)
GTEST_API_ void InitGoogleMock (int *argc, wchar_t **argv)
GTEST_DECLARE_string_ (death_test_style)
std::ostream & operator<< (std::ostream &os, const Message &sb)
template<typename T >
::std::string PrintToString (const T &value)
std::ostream & operator<< (std::ostream &os, const TestPartResult &result)
GTEST_DECLARE_bool_ (also_run_disabled_tests)
GTEST_DECLARE_bool_ (break_on_failure)
GTEST_DECLARE_bool_ (catch_exceptions)
GTEST_DECLARE_string_ (color)
GTEST_DECLARE_string_ (filter)
GTEST_DECLARE_bool_ (list_tests)
GTEST_DECLARE_string_ (output)
GTEST_DECLARE_bool_ (print_time)
GTEST_DECLARE_int32_ (random_seed)
GTEST_DECLARE_int32_ (repeat)
GTEST_DECLARE_bool_ (show_internal_stack_frames)
GTEST_DECLARE_bool_ (shuffle)
GTEST_DECLARE_int32_ (stack_trace_depth)
GTEST_DECLARE_bool_ (throw_on_failure)
GTEST_DECLARE_string_ (stream_result_to)
GTEST_API_ AssertionResult AssertionSuccess ()
GTEST_API_ AssertionResult AssertionFailure ()
GTEST_API_ AssertionResult AssertionFailure (const Message &msg)
Environment * AddGlobalTestEnvironment (Environment *env)
GTEST_API_ void InitGoogleTest (int *argc, char **argv)
GTEST_API_ void InitGoogleTest (int *argc, wchar_t **argv)
GTEST_API_ AssertionResult IsSubstring (const char *needle_expr, const char *haystack_expr, const char *needle, const char *haystack)
GTEST_API_ AssertionResult IsSubstring (const char *needle_expr, const char *haystack_expr, const wchar_t *needle, const wchar_t *haystack)
GTEST_API_ AssertionResult IsNotSubstring (const char *needle_expr, const char *haystack_expr, const char *needle, const char *haystack)
GTEST_API_ AssertionResult IsNotSubstring (const char *needle_expr, const char *haystack_expr, const wchar_t *needle, const wchar_t *haystack)
GTEST_API_ AssertionResult IsSubstring (const char *needle_expr, const char *haystack_expr, const ::std::string &needle, const ::std::string &haystack)
GTEST_API_ AssertionResult IsNotSubstring (const char *needle_expr, const char *haystack_expr, const ::std::string &needle, const ::std::string &haystack)
GTEST_API_ AssertionResult FloatLE (const char *expr1, const char *expr2, float val1, float val2)
GTEST_API_ AssertionResult DoubleLE (const char *expr1, const char *expr2, double val1, double val2)
template<typename T1 , typename T2 >
bool StaticAssertTypeEq ()
GTEST_DECLARE_bool_ (death_test_use_fork)
Variables
const internal::AnythingMatcher _ = {}
class GTEST_API_ testing::InSequence GTEST_ATTRIBUTE_UNUSED_
const int kMaxStackTraceDepth = 100
Typedef Documentation
TimeInMillis
typedef internal::TimeInMillis testing::TimeInMillis
Unused
typedef internal::IgnoredValue testing::Unused
Function Documentation
A()
template<typename T > Matcher< T > testing::A () inline
References MakeMatcher().
Referenced by testing::internal::OnCallSpec< F >::OnCallSpec(), and testing::internal::TypedExpectation< F >::TypedExpectation().
ACTION_P()
testing::ACTION_P (ReturnPointee , pointer)
ACTION_TEMPLATE() [1/28]
testing::ACTION_TEMPLATE (DeleteArg , HAS_1_TEMPLATE_PARAMS(int, k) , AND_0_VALUE_PARAMS())
ACTION_TEMPLATE() [2/28]
testing::ACTION_TEMPLATE (InvokeArgument , HAS_1_TEMPLATE_PARAMS(int, k) , AND_0_VALUE_PARAMS())
References testing::internal::CallableHelper< R >::Call().
ACTION_TEMPLATE() [3/28]
testing::ACTION_TEMPLATE (InvokeArgument , HAS_1_TEMPLATE_PARAMS(int, k) , AND_10_VALUE_PARAMS(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9))
References testing::internal::CallableHelper< R >::Call().
ACTION_TEMPLATE() [4/28]
testing::ACTION_TEMPLATE (InvokeArgument , HAS_1_TEMPLATE_PARAMS(int, k) , AND_1_VALUE_PARAMS(p0))
References testing::internal::CallableHelper< R >::Call().
ACTION_TEMPLATE() [5/28]
testing::ACTION_TEMPLATE (InvokeArgument , HAS_1_TEMPLATE_PARAMS(int, k) , AND_2_VALUE_PARAMS(p0, p1))
References testing::internal::CallableHelper< R >::Call().
ACTION_TEMPLATE() [6/28]
testing::ACTION_TEMPLATE (InvokeArgument , HAS_1_TEMPLATE_PARAMS(int, k) , AND_3_VALUE_PARAMS(p0, p1, p2))
References testing::internal::CallableHelper< R >::Call().
ACTION_TEMPLATE() [7/28]
testing::ACTION_TEMPLATE (InvokeArgument , HAS_1_TEMPLATE_PARAMS(int, k) , AND_4_VALUE_PARAMS(p0, p1, p2, p3))
References testing::internal::CallableHelper< R >::Call().
ACTION_TEMPLATE() [8/28]
testing::ACTION_TEMPLATE (InvokeArgument , HAS_1_TEMPLATE_PARAMS(int, k) , AND_5_VALUE_PARAMS(p0, p1, p2, p3, p4))
References testing::internal::CallableHelper< R >::Call().
ACTION_TEMPLATE() [9/28]
testing::ACTION_TEMPLATE (InvokeArgument , HAS_1_TEMPLATE_PARAMS(int, k) , AND_6_VALUE_PARAMS(p0, p1, p2, p3, p4, p5))
References testing::internal::CallableHelper< R >::Call().
ACTION_TEMPLATE() [10/28]
testing::ACTION_TEMPLATE (InvokeArgument , HAS_1_TEMPLATE_PARAMS(int, k) , AND_7_VALUE_PARAMS(p0, p1, p2, p3, p4, p5, p6))
References testing::internal::CallableHelper< R >::Call().
ACTION_TEMPLATE() [11/28]
testing::ACTION_TEMPLATE (InvokeArgument , HAS_1_TEMPLATE_PARAMS(int, k) , AND_8_VALUE_PARAMS(p0, p1, p2, p3, p4, p5, p6, p7))
References testing::internal::CallableHelper< R >::Call().
ACTION_TEMPLATE() [12/28]
testing::ACTION_TEMPLATE (InvokeArgument , HAS_1_TEMPLATE_PARAMS(int, k) , AND_9_VALUE_PARAMS(p0, p1, p2, p3, p4, p5, p6, p7, p8))
References testing::internal::CallableHelper< R >::Call().
ACTION_TEMPLATE() [13/28]
testing::ACTION_TEMPLATE (ReturnArg , HAS_1_TEMPLATE_PARAMS(int, k) , AND_0_VALUE_PARAMS())
ACTION_TEMPLATE() [14/28]
testing::ACTION_TEMPLATE (ReturnNew , HAS_1_TEMPLATE_PARAMS(typename, T) , AND_0_VALUE_PARAMS())
ACTION_TEMPLATE() [15/28]
testing::ACTION_TEMPLATE (ReturnNew , HAS_1_TEMPLATE_PARAMS(typename, T) , AND_10_VALUE_PARAMS(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9))
ACTION_TEMPLATE() [16/28]
testing::ACTION_TEMPLATE (ReturnNew , HAS_1_TEMPLATE_PARAMS(typename, T) , AND_1_VALUE_PARAMS(p0))
ACTION_TEMPLATE() [17/28]
testing::ACTION_TEMPLATE (ReturnNew , HAS_1_TEMPLATE_PARAMS(typename, T) , AND_2_VALUE_PARAMS(p0, p1))
ACTION_TEMPLATE() [18/28]
testing::ACTION_TEMPLATE (ReturnNew , HAS_1_TEMPLATE_PARAMS(typename, T) , AND_3_VALUE_PARAMS(p0, p1, p2))
ACTION_TEMPLATE() [19/28]
testing::ACTION_TEMPLATE (ReturnNew , HAS_1_TEMPLATE_PARAMS(typename, T) , AND_4_VALUE_PARAMS(p0, p1, p2, p3))
ACTION_TEMPLATE() [20/28]
testing::ACTION_TEMPLATE (ReturnNew , HAS_1_TEMPLATE_PARAMS(typename, T) , AND_5_VALUE_PARAMS(p0, p1, p2, p3, p4))
ACTION_TEMPLATE() [21/28]
testing::ACTION_TEMPLATE (ReturnNew , HAS_1_TEMPLATE_PARAMS(typename, T) , AND_6_VALUE_PARAMS(p0, p1, p2, p3, p4, p5))
ACTION_TEMPLATE() [22/28]
testing::ACTION_TEMPLATE (ReturnNew , HAS_1_TEMPLATE_PARAMS(typename, T) , AND_7_VALUE_PARAMS(p0, p1, p2, p3, p4, p5, p6))
ACTION_TEMPLATE() [23/28]
testing::ACTION_TEMPLATE (ReturnNew , HAS_1_TEMPLATE_PARAMS(typename, T) , AND_8_VALUE_PARAMS(p0, p1, p2, p3, p4, p5, p6, p7))
ACTION_TEMPLATE() [24/28]
testing::ACTION_TEMPLATE (ReturnNew , HAS_1_TEMPLATE_PARAMS(typename, T) , AND_9_VALUE_PARAMS(p0, p1, p2, p3, p4, p5, p6, p7, p8))
ACTION_TEMPLATE() [25/28]
testing::ACTION_TEMPLATE (SaveArg , HAS_1_TEMPLATE_PARAMS(int, k) , AND_1_VALUE_PARAMS(pointer))
ACTION_TEMPLATE() [26/28]
testing::ACTION_TEMPLATE (SaveArgPointee , HAS_1_TEMPLATE_PARAMS(int, k) , AND_1_VALUE_PARAMS(pointer))
ACTION_TEMPLATE() [27/28]
testing::ACTION_TEMPLATE (SetArgReferee , HAS_1_TEMPLATE_PARAMS(int, k) , AND_1_VALUE_PARAMS(value))
References GTEST_COMPILE_ASSERT_.
ACTION_TEMPLATE() [28/28]
testing::ACTION_TEMPLATE (SetArrayArgument , HAS_1_TEMPLATE_PARAMS(int, k) , AND_2_VALUE_PARAMS(first, last))
AddGlobalTestEnvironment()
Environment * testing::AddGlobalTestEnvironment (Environment * env) inline
AllArgs()
template<typename InnerMatcher > InnerMatcher testing::AllArgs (const InnerMatcher & matcher) inline
AllOf() [1/9]
template<typename M1 , typename M2 > internal::AllOfResult2< M1, M2 >::type testing::AllOf (M1 m1, M2 m2) inline
Referenced by AllOf(), AllOf(), AllOf(), AllOf(), AllOf(), AllOf(), AllOf(), and AllOf().
AllOf() [2/9]
template<typename M1 , typename M2 , typename M3 > internal::AllOfResult3< M1, M2, M3 >::type testing::AllOf (M1 m1, M2 m2, M3 m3) inline
References AllOf().
AllOf() [3/9]
template<typename M1 , typename M2 , typename M3 , typename M4 > internal::AllOfResult4< M1, M2, M3, M4 >::type testing::AllOf (M1 m1, M2 m2, M3 m3, M4 m4) inline
References AllOf().
AllOf() [4/9]
template<typename M1 , typename M2 , typename M3 , typename M4 , typename M5 > internal::AllOfResult5< M1, M2, M3, M4, M5 >::type testing::AllOf (M1 m1, M2 m2, M3 m3, M4 m4, M5 m5) inline
References AllOf().
AllOf() [5/9]
template<typename M1 , typename M2 , typename M3 , typename M4 , typename M5 , typename M6 > internal::AllOfResult6< M1, M2, M3, M4, M5, M6 >::type testing::AllOf (M1 m1, M2 m2, M3 m3, M4 m4, M5 m5, M6 m6) inline
References AllOf().
AllOf() [6/9]
template<typename M1 , typename M2 , typename M3 , typename M4 , typename M5 , typename M6 , typename M7 > internal::AllOfResult7< M1, M2, M3, M4, M5, M6, M7 >::type testing::AllOf (M1 m1, M2 m2, M3 m3, M4 m4, M5 m5, M6 m6, M7 m7) inline
References AllOf().
AllOf() [7/9]
template<typename M1 , typename M2 , typename M3 , typename M4 , typename M5 , typename M6 , typename M7 , typename M8 > internal::AllOfResult8< M1, M2, M3, M4, M5, M6, M7, M8 >::type testing::AllOf (M1 m1, M2 m2, M3 m3, M4 m4, M5 m5, M6 m6, M7 m7, M8 m8) inline
References AllOf().
AllOf() [8/9]
template<typename M1 , typename M2 , typename M3 , typename M4 , typename M5 , typename M6 , typename M7 , typename M8 , typename M9 > internal::AllOfResult9< M1, M2, M3, M4, M5, M6, M7, M8, M9 >::type testing::AllOf (M1 m1, M2 m2, M3 m3, M4 m4, M5 m5, M6 m6, M7 m7, M8 m8, M9 m9) inline
References AllOf().
AllOf() [9/9]
template<typename M1 , typename M2 , typename M3 , typename M4 , typename M5 , typename M6 , typename M7 , typename M8 , typename M9 , typename M10 > internal::AllOfResult10< M1, M2, M3, M4, M5, M6, M7, M8, M9, M10 >::type testing::AllOf (M1 m1, M2 m2, M3 m3, M4 m4, M5 m5, M6 m6, M7 m7, M8 m8, M9 m9, M10 m10) inline
References AllOf().
An()
template<typename T > Matcher< T > testing::An () inline
AnyNumber()
GTEST_API_ Cardinality testing::AnyNumber ()
AnyOf() [1/9]
template<typename M1 , typename M2 > internal::AnyOfResult2< M1, M2 >::type testing::AnyOf (M1 m1, M2 m2) inline
Referenced by AnyOf(), AnyOf(), AnyOf(), AnyOf(), AnyOf(), AnyOf(), AnyOf(), and AnyOf().
AnyOf() [2/9]
template<typename M1 , typename M2 , typename M3 > internal::AnyOfResult3< M1, M2, M3 >::type testing::AnyOf (M1 m1, M2 m2, M3 m3) inline
References AnyOf().
AnyOf() [3/9]
template<typename M1 , typename M2 , typename M3 , typename M4 > internal::AnyOfResult4< M1, M2, M3, M4 >::type testing::AnyOf (M1 m1, M2 m2, M3 m3, M4 m4) inline
References AnyOf().
AnyOf() [4/9]
template<typename M1 , typename M2 , typename M3 , typename M4 , typename M5 > internal::AnyOfResult5< M1, M2, M3, M4, M5 >::type testing::AnyOf (M1 m1, M2 m2, M3 m3, M4 m4, M5 m5) inline
References AnyOf().
AnyOf() [5/9]
template<typename M1 , typename M2 , typename M3 , typename M4 , typename M5 , typename M6 > internal::AnyOfResult6< M1, M2, M3, M4, M5, M6 >::type testing::AnyOf (M1 m1, M2 m2, M3 m3, M4 m4, M5 m5, M6 m6) inline
References AnyOf().
AnyOf() [6/9]
template<typename M1 , typename M2 , typename M3 , typename M4 , typename M5 , typename M6 , typename M7 > internal::AnyOfResult7< M1, M2, M3, M4, M5, M6, M7 >::type testing::AnyOf (M1 m1, M2 m2, M3 m3, M4 m4, M5 m5, M6 m6, M7 m7) inline
References AnyOf().
AnyOf() [7/9]
template<typename M1 , typename M2 , typename M3 , typename M4 , typename M5 , typename M6 , typename M7 , typename M8 > internal::AnyOfResult8< M1, M2, M3, M4, M5, M6, M7, M8 >::type testing::AnyOf (M1 m1, M2 m2, M3 m3, M4 m4, M5 m5, M6 m6, M7 m7, M8 m8) inline
References AnyOf().
AnyOf() [8/9]
template<typename M1 , typename M2 , typename M3 , typename M4 , typename M5 , typename M6 , typename M7 , typename M8 , typename M9 > internal::AnyOfResult9< M1, M2, M3, M4, M5, M6, M7, M8, M9 >::type testing::AnyOf (M1 m1, M2 m2, M3 m3, M4 m4, M5 m5, M6 m6, M7 m7, M8 m8, M9 m9) inline
References AnyOf().
AnyOf() [9/9]
template<typename M1 , typename M2 , typename M3 , typename M4 , typename M5 , typename M6 , typename M7 , typename M8 , typename M9 , typename M10 > internal::AnyOfResult10< M1, M2, M3, M4, M5, M6, M7, M8, M9, M10 >::type testing::AnyOf (M1 m1, M2 m2, M3 m3, M4 m4, M5 m5, M6 m6, M7 m7, M8 m8, M9 m9, M10 m10) inline
References AnyOf().
Args() [1/11]
template<typename InnerMatcher > internal::ArgsMatcher< InnerMatcher > testing::Args (const InnerMatcher & matcher) inline
Referenced by ElementsAre(), ElementsAre(), ElementsAre(), ElementsAre(), ElementsAre(), ElementsAre(), ElementsAre(), ElementsAre(), ElementsAre(), ElementsAre(), ElementsAre(), UnorderedElementsAre(), UnorderedElementsAre(), UnorderedElementsAre(), UnorderedElementsAre(), UnorderedElementsAre(), UnorderedElementsAre(), UnorderedElementsAre(), UnorderedElementsAre(), UnorderedElementsAre(), UnorderedElementsAre(), and UnorderedElementsAre().
Args() [2/11]
template<int k1, typename InnerMatcher > internal::ArgsMatcher< InnerMatcher, k1 > testing::Args (const InnerMatcher & matcher) inline
Args() [3/11]
template<int k1, int k2, typename InnerMatcher > internal::ArgsMatcher< InnerMatcher, k1, k2 > testing::Args (const InnerMatcher & matcher) inline
Args() [4/11]
template<int k1, int k2, int k3, typename InnerMatcher > internal::ArgsMatcher< InnerMatcher, k1, k2, k3 > testing::Args (const InnerMatcher & matcher) inline
Args() [5/11]
template<int k1, int k2, int k3, int k4, typename InnerMatcher > internal::ArgsMatcher< InnerMatcher, k1, k2, k3, k4 > testing::Args (const InnerMatcher & matcher) inline
Args() [6/11]
template<int k1, int k2, int k3, int k4, int k5, typename InnerMatcher > internal::ArgsMatcher< InnerMatcher, k1, k2, k3, k4, k5 > testing::Args (const InnerMatcher & matcher) inline
Args() [7/11]
template<int k1, int k2, int k3, int k4, int k5, int k6, typename InnerMatcher > internal::ArgsMatcher< InnerMatcher, k1, k2, k3, k4, k5, k6 > testing::Args (const InnerMatcher & matcher) inline
Args() [8/11]
template<int k1, int k2, int k3, int k4, int k5, int k6, int k7, typename InnerMatcher > internal::ArgsMatcher< InnerMatcher, k1, k2, k3, k4, k5, k6, k7 > testing::Args (const InnerMatcher & matcher) inline
Args() [9/11]
template<int k1, int k2, int k3, int k4, int k5, int k6, int k7, int k8, typename InnerMatcher > internal::ArgsMatcher< InnerMatcher, k1, k2, k3, k4, k5, k6, k7, k8 > testing::Args (const InnerMatcher & matcher) inline
Args() [10/11]
template<int k1, int k2, int k3, int k4, int k5, int k6, int k7, int k8, int k9, typename InnerMatcher > internal::ArgsMatcher< InnerMatcher, k1, k2, k3, k4, k5, k6, k7, k8, k9 > testing::Args (const InnerMatcher & matcher) inline
Args() [11/11]
template<int k1, int k2, int k3, int k4, int k5, int k6, int k7, int k8, int k9, int k10, typename InnerMatcher > internal::ArgsMatcher< InnerMatcher, k1, k2, k3, k4, k5, k6, k7, k8, k9, k10 > testing::Args (const InnerMatcher & matcher) inline
AssertionFailure() [1/2]
GTEST_API_ AssertionResult testing::AssertionFailure ()
Referenced by testing::internal::PredicateFormatterFromMatcher< M >::operator()().
AssertionFailure() [2/2]
GTEST_API_ AssertionResult testing::AssertionFailure (const Message & msg)
AssertionSuccess()
GTEST_API_ AssertionResult testing::AssertionSuccess ()
Referenced by testing::internal::CmpHelperFloatingPointEQ(), and testing::internal::PredicateFormatterFromMatcher< M >::operator()().
Assign()
template<typename T1 , typename T2 > PolymorphicAction< internal::AssignAction< T1, T2 > > testing::Assign (T1 * ptr, T2 val)
References MakePolymorphicAction().
AtLeast()
GTEST_API_ Cardinality testing::AtLeast (int n)
Referenced by testing::internal::TypedExpectation< F >::WillRepeatedly().
AtMost()
GTEST_API_ Cardinality testing::AtMost (int n)
Between()
GTEST_API_ Cardinality testing::Between (int min, int max)
ByRef()
template<typename T > internal::ReferenceWrapper< T > testing::ByRef (T & l_value) inline
Const()
template<typename T > const T & testing::Const (const T & x) inline
ContainerEq()
template<typename Container > PolymorphicMatcher< internal::ContainerEqMatcher< GTEST_REMOVE_CONST_(Container)> > testing::ContainerEq (const Container & rhs) inline
References GTEST_REMOVE_CONST_, and MakePolymorphicMatcher().
Contains()
template<typename M > internal::ContainsMatcher< M > testing::Contains (M matcher) inline
ContainsRegex() [1/2]
PolymorphicMatcher< internal::MatchesRegexMatcher > testing::ContainsRegex (const internal::RE * regex) inline
References MakePolymorphicMatcher().
Referenced by ContainsRegex().
ContainsRegex() [2/2]
PolymorphicMatcher< internal::MatchesRegexMatcher > testing::ContainsRegex (const internal::string & regex) inline
References ContainsRegex().
DoAll() [1/9]
template<typename Action1 , typename Action2 > internal::DoBothAction< Action1, Action2 > testing::DoAll (Action1 a1, Action2 a2) inline
Referenced by DoAll(), DoAll(), DoAll(), DoAll(), DoAll(), DoAll(), DoAll(), and DoAll().
DoAll() [2/9]
template<typename Action1 , typename Action2 , typename Action3 > internal::DoBothAction< Action1, internal::DoBothAction< Action2, Action3 > > testing::DoAll (Action1 a1, Action2 a2, Action3 a3) inline
References DoAll().
DoAll() [3/9]
template<typename Action1 , typename Action2 , typename Action3 , typename Action4 > internal::DoBothAction< Action1, internal::DoBothAction< Action2, internal::DoBothAction< Action3, Action4 > > > testing::DoAll (Action1 a1, Action2 a2, Action3 a3, Action4 a4) inline
References DoAll().
DoAll() [4/9]
template<typename Action1 , typename Action2 , typename Action3 , typename Action4 , typename Action5 > internal::DoBothAction< Action1, internal::DoBothAction< Action2, internal::DoBothAction< Action3, internal::DoBothAction< Action4, Action5 > > > > testing::DoAll (Action1 a1, Action2 a2, Action3 a3, Action4 a4, Action5 a5) inline
References DoAll().
DoAll() [5/9]
template<typename Action1 , typename Action2 , typename Action3 , typename Action4 , typename Action5 , typename Action6 > internal::DoBothAction< Action1, internal::DoBothAction< Action2, internal::DoBothAction< Action3, internal::DoBothAction< Action4, internal::DoBothAction< Action5, Action6 > > > > > testing::DoAll (Action1 a1, Action2 a2, Action3 a3, Action4 a4, Action5 a5, Action6 a6) inline
References DoAll().
DoAll() [6/9]
template<typename Action1 , typename Action2 , typename Action3 , typename Action4 , typename Action5 , typename Action6 , typename Action7 > internal::DoBothAction< Action1, internal::DoBothAction< Action2, internal::DoBothAction< Action3, internal::DoBothAction< Action4, internal::DoBothAction< Action5, internal::DoBothAction< Action6, Action7 > > > > > > testing::DoAll (Action1 a1, Action2 a2, Action3 a3, Action4 a4, Action5 a5, Action6 a6, Action7 a7) inline
References DoAll().
DoAll() [7/9]
template<typename Action1 , typename Action2 , typename Action3 , typename Action4 , typename Action5 , typename Action6 , typename Action7 , typename Action8 > internal::DoBothAction< Action1, internal::DoBothAction< Action2, internal::DoBothAction< Action3, internal::DoBothAction< Action4, internal::DoBothAction< Action5, internal::DoBothAction< Action6, internal::DoBothAction< Action7, Action8 > > > > > > > testing::DoAll (Action1 a1, Action2 a2, Action3 a3, Action4 a4, Action5 a5, Action6 a6, Action7 a7, Action8 a8) inline
References DoAll().
DoAll() [8/9]
template<typename Action1 , typename Action2 , typename Action3 , typename Action4 , typename Action5 , typename Action6 , typename Action7 , typename Action8 , typename Action9 > internal::DoBothAction< Action1, internal::DoBothAction< Action2, internal::DoBothAction< Action3, internal::DoBothAction< Action4, internal::DoBothAction< Action5, internal::DoBothAction< Action6, internal::DoBothAction< Action7, internal::DoBothAction< Action8, Action9 > > > > > > > > testing::DoAll (Action1 a1, Action2 a2, Action3 a3, Action4 a4, Action5 a5, Action6 a6, Action7 a7, Action8 a8, Action9 a9) inline
References DoAll().
DoAll() [9/9]
template<typename Action1 , typename Action2 , typename Action3 , typename Action4 , typename Action5 , typename Action6 , typename Action7 , typename Action8 , typename Action9 , typename Action10 > internal::DoBothAction< Action1, internal::DoBothAction< Action2, internal::DoBothAction< Action3, internal::DoBothAction< Action4, internal::DoBothAction< Action5, internal::DoBothAction< Action6, internal::DoBothAction< Action7, internal::DoBothAction< Action8, internal::DoBothAction< Action9, Action10 > > > > > > > > > testing::DoAll (Action1 a1, Action2 a2, Action3 a3, Action4 a4, Action5 a5, Action6 a6, Action7 a7, Action8 a8, Action9 a9, Action10 a10) inline
References DoAll().
DoDefault()
internal::DoDefaultAction testing::DoDefault () inline
Referenced by testing::internal::TypedExpectation< F >::TypedExpectation().
DoubleEq()
internal::FloatingEqMatcher< double > testing::DoubleEq (double rhs) inline
DoubleLE()
GTEST_API_ AssertionResult testing::DoubleLE (const char * expr1, const char * expr2, double val1, double val2)
References DoubleLE().
Referenced by DoubleLE().
DoubleNear()
internal::FloatingEqMatcher< double > testing::DoubleNear (double rhs, double max_abs_error) inline
Each()
template<typename M > internal::EachMatcher< M > testing::Each (M matcher) inline
ElementsAre() [1/11]
internal::ElementsAreMatcher< std::tr1::tuple<> > testing::ElementsAre () inline
References Args().
ElementsAre() [2/11]
template<typename T1 > internal::ElementsAreMatcher< std::tr1::tuple< typename internal::DecayArray< T1 >::type > > testing::ElementsAre (const T1 & e1) inline
References Args().
ElementsAre() [3/11]
template<typename T1 , typename T2 > internal::ElementsAreMatcher< std::tr1::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type > > testing::ElementsAre (const T1 & e1, const T2 & e2) inline
References Args().
ElementsAre() [4/11]
template<typename T1 , typename T2 , typename T3 > internal::ElementsAreMatcher< std::tr1::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type > > testing::ElementsAre (const T1 & e1, const T2 & e2, const T3 & e3) inline
References Args().
ElementsAre() [5/11]
template<typename T1 , typename T2 , typename T3 , typename T4 > internal::ElementsAreMatcher< std::tr1::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type > > testing::ElementsAre (const T1 & e1, const T2 & e2, const T3 & e3, const T4 & e4) inline
References Args().
ElementsAre() [6/11]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 > internal::ElementsAreMatcher< std::tr1::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type, typename internal::DecayArray< T5 >::type > > testing::ElementsAre (const T1 & e1, const T2 & e2, const T3 & e3, const T4 & e4, const T5 & e5) inline
References Args().
ElementsAre() [7/11]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 > internal::ElementsAreMatcher< std::tr1::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type, typename internal::DecayArray< T5 >::type, typename internal::DecayArray< T6 >::type > > testing::ElementsAre (const T1 & e1, const T2 & e2, const T3 & e3, const T4 & e4, const T5 & e5, const T6 & e6) inline
References Args().
ElementsAre() [8/11]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 > internal::ElementsAreMatcher< std::tr1::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type, typename internal::DecayArray< T5 >::type, typename internal::DecayArray< T6 >::type, typename internal::DecayArray< T7 >::type > > testing::ElementsAre (const T1 & e1, const T2 & e2, const T3 & e3, const T4 & e4, const T5 & e5, const T6 & e6, const T7 & e7) inline
References Args().
ElementsAre() [9/11]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 > internal::ElementsAreMatcher< std::tr1::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type, typename internal::DecayArray< T5 >::type, typename internal::DecayArray< T6 >::type, typename internal::DecayArray< T7 >::type, typename internal::DecayArray< T8 >::type > > testing::ElementsAre (const T1 & e1, const T2 & e2, const T3 & e3, const T4 & e4, const T5 & e5, const T6 & e6, const T7 & e7, const T8 & e8) inline
References Args().
ElementsAre() [10/11]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 > internal::ElementsAreMatcher< std::tr1::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type, typename internal::DecayArray< T5 >::type, typename internal::DecayArray< T6 >::type, typename internal::DecayArray< T7 >::type, typename internal::DecayArray< T8 >::type, typename internal::DecayArray< T9 >::type > > testing::ElementsAre (const T1 & e1, const T2 & e2, const T3 & e3, const T4 & e4, const T5 & e5, const T6 & e6, const T7 & e7, const T8 & e8, const T9 & e9) inline
References Args().
ElementsAre() [11/11]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 > internal::ElementsAreMatcher< std::tr1::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type, typename internal::DecayArray< T5 >::type, typename internal::DecayArray< T6 >::type, typename internal::DecayArray< T7 >::type, typename internal::DecayArray< T8 >::type, typename internal::DecayArray< T9 >::type, typename internal::DecayArray< T10 >::type > > testing::ElementsAre (const T1 & e1, const T2 & e2, const T3 & e3, const T4 & e4, const T5 & e5, const T6 & e6, const T7 & e7, const T8 & e8, const T9 & e9, const T10 & e10) inline
References Args().
ElementsAreArray() [1/4]
template<typename T , typename A > internal::ElementsAreArrayMatcher< T > testing::ElementsAreArray (const ::std::vector< T, A > & vec) inline
References ElementsAreArray().
ElementsAreArray() [2/4]
template<typename T > internal::ElementsAreArrayMatcher< T > testing::ElementsAreArray (const T * pointer, size_t count) inline
References ElementsAreArray().
ElementsAreArray() [3/4]
template<typename T , size_t N> internal::ElementsAreArrayMatcher< T > testing::ElementsAreArray (const T(&) array[N]) inline
References ElementsAreArray().
ElementsAreArray() [4/4]
template<typename Iter > internal::ElementsAreArrayMatcher< typename ::std::iterator_traits< Iter >::value_type > testing::ElementsAreArray (Iter first, Iter last) inline
Referenced by ElementsAreArray(), ElementsAreArray(), and ElementsAreArray().
EndsWith()
PolymorphicMatcher< internal::EndsWithMatcher< internal::string > > testing::EndsWith (const internal::string & suffix) inline
References MakePolymorphicMatcher().
Eq() [1/2]
internal::Eq2Matcher testing::Eq () inline
Referenced by testing::Matcher< T >::Matcher(), and TypedEq().
Eq() [2/2]
template<typename T > internal::EqMatcher< T > testing::Eq (T x) inline
Exactly()
GTEST_API_ Cardinality testing::Exactly (int n)
Referenced by testing::internal::TypedExpectation< F >::Times(), and testing::internal::TypedExpectation< F >::WillOnce().
ExplainMatchResult()
template<typename T , typename M > bool testing::ExplainMatchResult (M matcher, const T & value, MatchResultListener * listener) inline
Field()
template<typename Class , typename FieldType , typename FieldMatcher > PolymorphicMatcher< internal::FieldMatcher< Class, FieldType > > testing::Field (FieldType Class::* field, const FieldMatcher & matcher) inline
References MakePolymorphicMatcher().
FloatEq()
internal::FloatingEqMatcher< float > testing::FloatEq (float rhs) inline
FloatLE()
GTEST_API_ AssertionResult testing::FloatLE (const char * expr1, const char * expr2, float val1, float val2)
References FloatLE().
Referenced by FloatLE().
FloatNear()
internal::FloatingEqMatcher< float > testing::FloatNear (float rhs, float max_abs_error) inline
Ge() [1/2]
internal::Ge2Matcher testing::Ge () inline
Ge() [2/2]
template<typename Rhs > internal::GeMatcher< Rhs > testing::Ge (Rhs x) inline
GMOCK_DECLARE_bool_()
testing::GMOCK_DECLARE_bool_ (catch_leaked_mocks)
GMOCK_DECLARE_string_()
testing::GMOCK_DECLARE_string_ (verbose)
Gt() [1/2]
internal::Gt2Matcher testing::Gt () inline
Gt() [2/2]
template<typename Rhs > internal::GtMatcher< Rhs > testing::Gt (Rhs x) inline
GTEST_DECLARE_bool_() [1/9]
testing::GTEST_DECLARE_bool_ (also_run_disabled_tests)
GTEST_DECLARE_bool_() [2/9]
testing::GTEST_DECLARE_bool_ (break_on_failure)
GTEST_DECLARE_bool_() [3/9]
testing::GTEST_DECLARE_bool_ (catch_exceptions)
GTEST_DECLARE_bool_() [4/9]
testing::GTEST_DECLARE_bool_ (death_test_use_fork)
GTEST_DECLARE_bool_() [5/9]
testing::GTEST_DECLARE_bool_ (list_tests)
GTEST_DECLARE_bool_() [6/9]
testing::GTEST_DECLARE_bool_ (print_time)
GTEST_DECLARE_bool_() [7/9]
testing::GTEST_DECLARE_bool_ (show_internal_stack_frames)
GTEST_DECLARE_bool_() [8/9]
testing::GTEST_DECLARE_bool_ (shuffle)
GTEST_DECLARE_bool_() [9/9]
testing::GTEST_DECLARE_bool_ (throw_on_failure)
GTEST_DECLARE_int32_() [1/3]
testing::GTEST_DECLARE_int32_ (random_seed)
GTEST_DECLARE_int32_() [2/3]
testing::GTEST_DECLARE_int32_ (repeat)
GTEST_DECLARE_int32_() [3/3]
testing::GTEST_DECLARE_int32_ (stack_trace_depth)
GTEST_DECLARE_string_() [1/5]
testing::GTEST_DECLARE_string_ (color)
GTEST_DECLARE_string_() [2/5]
testing::GTEST_DECLARE_string_ (death_test_style)
GTEST_DECLARE_string_() [3/5]
testing::GTEST_DECLARE_string_ (filter)
GTEST_DECLARE_string_() [4/5]
testing::GTEST_DECLARE_string_ (output)
GTEST_DECLARE_string_() [5/5]
testing::GTEST_DECLARE_string_ (stream_result_to)
HasSubstr()
PolymorphicMatcher< internal::HasSubstrMatcher< internal::string > > testing::HasSubstr (const internal::string & substring) inline
References MakePolymorphicMatcher().
IgnoreResult()
template<typename A > internal::IgnoreResultAction< A > testing::IgnoreResult (const A & an_action) inline
InitGoogleMock() [1/2]
GTEST_API_ void testing::InitGoogleMock (int * argc, char ** argv)
InitGoogleMock() [2/2]
GTEST_API_ void testing::InitGoogleMock (int * argc, wchar_t ** argv)
InitGoogleTest() [1/2]
GTEST_API_ void testing::InitGoogleTest (int * argc, char ** argv)
References InitGoogleTest().
Referenced by InitGoogleTest(), and InitGoogleTest().
InitGoogleTest() [2/2]
GTEST_API_ void testing::InitGoogleTest (int * argc, wchar_t ** argv)
References InitGoogleTest().
Invoke() [1/2]
template<class Class , typename MethodPtr > PolymorphicAction< internal::InvokeMethodAction< Class, MethodPtr > > testing::Invoke (Class * obj_ptr, MethodPtr method_ptr)
References MakePolymorphicAction().
Invoke() [2/2]
template<typename FunctionImpl > PolymorphicAction< internal::InvokeAction< FunctionImpl > > testing::Invoke (FunctionImpl function_impl)
References MakePolymorphicAction().
InvokeWithoutArgs() [1/2]
template<class Class , typename MethodPtr > PolymorphicAction< internal::InvokeMethodWithoutArgsAction< Class, MethodPtr > > testing::InvokeWithoutArgs (Class * obj_ptr, MethodPtr method_ptr)
References MakePolymorphicAction().
InvokeWithoutArgs() [2/2]
template<typename FunctionImpl > PolymorphicAction< internal::InvokeWithoutArgsAction< FunctionImpl > > testing::InvokeWithoutArgs (FunctionImpl function_impl)
References MakePolymorphicAction().
IsNotSubstring() [1/3]
GTEST_API_ AssertionResult testing::IsNotSubstring (const char * needle_expr, const char * haystack_expr, const ::std::string & needle, const ::std::string & haystack)
References IsNotSubstring(), and IsSubstring().
IsNotSubstring() [2/3]
GTEST_API_ AssertionResult testing::IsNotSubstring (const char * needle_expr, const char * haystack_expr, const char * needle, const char * haystack)
References IsNotSubstring().
Referenced by IsNotSubstring(), IsNotSubstring(), and IsNotSubstring().
IsNotSubstring() [3/3]
GTEST_API_ AssertionResult testing::IsNotSubstring (const char * needle_expr, const char * haystack_expr, const wchar_t * needle, const wchar_t * haystack)
References IsNotSubstring().
IsNull()
PolymorphicMatcher< internal::IsNullMatcher > testing::IsNull () inline
References MakePolymorphicMatcher().
IsSubstring() [1/3]
GTEST_API_ AssertionResult testing::IsSubstring (const char * needle_expr, const char * haystack_expr, const ::std::string & needle, const ::std::string & haystack)
References IsSubstring().
IsSubstring() [2/3]
GTEST_API_ AssertionResult testing::IsSubstring (const char * needle_expr, const char * haystack_expr, const char * needle, const char * haystack)
References IsSubstring().
Referenced by IsNotSubstring(), IsSubstring(), IsSubstring(), and IsSubstring().
IsSubstring() [3/3]
GTEST_API_ AssertionResult testing::IsSubstring (const char * needle_expr, const char * haystack_expr, const wchar_t * needle, const wchar_t * haystack)
References IsSubstring().
Key()
template<typename M > internal::KeyMatcher< M > testing::Key (M inner_matcher) inline
Le() [1/2]
internal::Le2Matcher testing::Le () inline
Le() [2/2]
template<typename Rhs > internal::LeMatcher< Rhs > testing::Le (Rhs x) inline
Lt() [1/2]
internal::Lt2Matcher testing::Lt () inline
Lt() [2/2]
template<typename Rhs > internal::LtMatcher< Rhs > testing::Lt (Rhs x) inline
MakeAction()
template<typename F > Action< F > testing::MakeAction (ActionInterface< F > * impl)
Referenced by testing::internal::WithArgsAction< InnerAction, k1, k2, k3, k4, k5, k6, k7, k8, k9, k10 >::operator Action< F >().
MakeCardinality()
Cardinality testing::MakeCardinality (const CardinalityInterface * c) inline
MakeMatcher()
template<typename T > Matcher< T > testing::MakeMatcher (const MatcherInterface< T > * impl) inline
Referenced by A(), testing::internal::ArgsMatcher< InnerMatcher, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::operator Matcher< ArgsTuple >(), testing::internal::FloatingEqMatcher< FloatType >::operator Matcher< const FloatType & >(), testing::internal::SizeIsMatcher< SizeMatcher >::operator Matcher< Container >(), testing::internal::ContainsMatcher< M >::operator Matcher< Container >(), testing::internal::EachMatcher< M >::operator Matcher< Container >(), testing::internal::UnorderedElementsAreMatcher< MatcherTuple >::operator Matcher< Container >(), testing::internal::ElementsAreMatcher< MatcherTuple >::operator Matcher< Container >(), testing::internal::UnorderedElementsAreArrayMatcher< T >::operator Matcher< Container >(), testing::internal::ElementsAreArrayMatcher< T >::operator Matcher< Container >(), testing::internal::FloatingEqMatcher< FloatType >::operator Matcher< FloatType & >(), testing::internal::FloatingEqMatcher< FloatType >::operator Matcher< FloatType >(), testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::operator Matcher< LhsContainer >(), testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::operator Matcher< LhsContainer >(), testing::internal::KeyMatcher< M >::operator Matcher< PairType >(), testing::internal::PairMatcher< FirstMatcher, SecondMatcher >::operator Matcher< PairType >(), testing::internal::PointeeMatcher< InnerMatcher >::operator Matcher< Pointer >(), and testing::internal::RefMatcher< T & >::operator Matcher< Super & >().
MakePolymorphicAction()
template<typename Impl > PolymorphicAction< Impl > testing::MakePolymorphicAction (const Impl & impl) inline
Referenced by Assign(), Invoke(), Invoke(), InvokeWithoutArgs(), InvokeWithoutArgs(), Return(), ReturnNull(), SetArgPointee(), SetArgPointee(), SetArgPointee(), SetArgumentPointee(), and SetErrnoAndReturn().
MakePolymorphicMatcher()
template<class Impl > PolymorphicMatcher< Impl > testing::MakePolymorphicMatcher (const Impl & impl) inline
Referenced by ContainerEq(), ContainsRegex(), EndsWith(), Field(), HasSubstr(), IsNull(), MatchesRegex(), NotNull(), Property(), StartsWith(), StrCaseEq(), StrCaseNe(), StrEq(), StrNe(), and Truly().
MATCHER()
testing::MATCHER (IsEmpty , negation ? "isn't empty" :"is empty")
MatcherCast()
template<typename T , typename M > Matcher< T > testing::MatcherCast (M matcher) inline
Referenced by Property(), and ResultOf().
Matches()
template<typename M > internal::MatcherAsPredicate< M > testing::Matches (M matcher) inline
Referenced by testing::internal::TupleMatches(), and Value().
MatchesRegex() [1/2]
PolymorphicMatcher< internal::MatchesRegexMatcher > testing::MatchesRegex (const internal::RE * regex) inline
References MakePolymorphicMatcher().
Referenced by MatchesRegex().
MatchesRegex() [2/2]
PolymorphicMatcher< internal::MatchesRegexMatcher > testing::MatchesRegex (const internal::string & regex) inline
References MatchesRegex().
NanSensitiveDoubleEq()
internal::FloatingEqMatcher< double > testing::NanSensitiveDoubleEq (double rhs) inline
NanSensitiveDoubleNear()
internal::FloatingEqMatcher< double > testing::NanSensitiveDoubleNear (double rhs, double max_abs_error) inline
NanSensitiveFloatEq()
internal::FloatingEqMatcher< float > testing::NanSensitiveFloatEq (float rhs) inline
NanSensitiveFloatNear()
internal::FloatingEqMatcher< float > testing::NanSensitiveFloatNear (float rhs, float max_abs_error) inline
Ne() [1/2]
internal::Ne2Matcher testing::Ne () inline
Ne() [2/2]
template<typename Rhs > internal::NeMatcher< Rhs > testing::Ne (Rhs x) inline
Not()
template<typename InnerMatcher > internal::NotMatcher< InnerMatcher > testing::Not (InnerMatcher m) inline
NotNull()
PolymorphicMatcher< internal::NotNullMatcher > testing::NotNull () inline
References MakePolymorphicMatcher().
operator<<() [1/2]
std::ostream & testing::operator<< (std::ostream & os, const Message & sb) inline
References testing::Message::GetString().
operator<<() [2/2]
std::ostream & testing::operator<< (std::ostream & os, const TestPartResult & result)
Pair()
template<typename FirstMatcher , typename SecondMatcher > internal::PairMatcher< FirstMatcher, SecondMatcher > testing::Pair (FirstMatcher first_matcher, SecondMatcher second_matcher) inline
Pointee()
template<typename InnerMatcher > internal::PointeeMatcher< InnerMatcher > testing::Pointee (const InnerMatcher & inner_matcher) inline
Pointwise()
template<typename TupleMatcher , typename Container > internal::PointwiseMatcher< TupleMatcher, GTEST_REMOVE_CONST_(Container)> testing::Pointwise (const TupleMatcher & tuple_matcher, const Container & rhs) inline
References GTEST_REMOVE_CONST_.
PrintToString()
template<typename T > ::std::string testing::PrintToString (const T & value)
References testing::internal::UniversalTersePrinter< T >::Print().
Referenced by testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::MatchAndExplain().
Property()
template<typename Class , typename PropertyType , typename PropertyMatcher > PolymorphicMatcher< internal::PropertyMatcher< Class, PropertyType > > testing::Property (PropertyType(Class::*)() const property, const PropertyMatcher & matcher) inline
References GTEST_REFERENCE_TO_CONST_, MakePolymorphicMatcher(), and MatcherCast().
Ref()
template<typename T > internal::RefMatcher< T & > testing::Ref (T & x) inline
ResultOf()
template<typename Callable , typename ResultOfMatcher > internal::ResultOfMatcher< Callable > testing::ResultOf (Callable callable, const ResultOfMatcher & matcher)
References MatcherCast().
Return() [1/2]
PolymorphicAction< internal::ReturnVoidAction > testing::Return () inline
References MakePolymorphicAction().
Return() [2/2]
template<typename R > internal::ReturnAction< R > testing::Return (R value)
ReturnNull()
PolymorphicAction< internal::ReturnNullAction > testing::ReturnNull () inline
References MakePolymorphicAction().
ReturnRef()
template<typename R > internal::ReturnRefAction< R > testing::ReturnRef (R & x) inline
ReturnRefOfCopy()
template<typename R > internal::ReturnRefOfCopyAction< R > testing::ReturnRefOfCopy (const R & x) inline
SafeMatcherCast()
template<typename T , typename M > Matcher< T > testing::SafeMatcherCast (const M & polymorphic_matcher) inline
References testing::SafeMatcherCastImpl< T >::Cast().
SetArgPointee() [1/3]
template<size_t N> PolymorphicAction< internal::SetArgumentPointeeAction< N, const char *, false > > testing::SetArgPointee (const char * p)
References MakePolymorphicAction().
SetArgPointee() [2/3]
template<size_t N, typename T > PolymorphicAction< internal::SetArgumentPointeeAction< N, T, internal::IsAProtocolMessage< T >::value > > testing::SetArgPointee (const T & x)
References MakePolymorphicAction().
SetArgPointee() [3/3]
template<size_t N> PolymorphicAction< internal::SetArgumentPointeeAction< N, const wchar_t *, false > > testing::SetArgPointee (const wchar_t * p)
References MakePolymorphicAction().
SetArgumentPointee()
template<size_t N, typename T > PolymorphicAction< internal::SetArgumentPointeeAction< N, T, internal::IsAProtocolMessage< T >::value > > testing::SetArgumentPointee (const T & x)
References MakePolymorphicAction().
SetErrnoAndReturn()
template<typename T > PolymorphicAction< internal::SetErrnoAndReturnAction< T > > testing::SetErrnoAndReturn (int errval, T result)
References MakePolymorphicAction().
SizeIs()
template<typename SizeMatcher > internal::SizeIsMatcher< SizeMatcher > testing::SizeIs (const SizeMatcher & size_matcher) inline
StartsWith()
PolymorphicMatcher< internal::StartsWithMatcher< internal::string > > testing::StartsWith (const internal::string & prefix) inline
References MakePolymorphicMatcher().
StaticAssertTypeEq()
template<typename T1 , typename T2 > bool testing::StaticAssertTypeEq ()
References StaticAssertTypeEq().
Referenced by testing::internal::StlContainerView< RawContainer >::ConstReference(), testing::internal::ContainerEqMatcher< Container >::ContainerEqMatcher(), testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::PointwiseMatcher(), and StaticAssertTypeEq().
StrCaseEq()
PolymorphicMatcher< internal::StrEqualityMatcher< internal::string > > testing::StrCaseEq (const internal::string & str) inline
References MakePolymorphicMatcher().
StrCaseNe()
PolymorphicMatcher< internal::StrEqualityMatcher< internal::string > > testing::StrCaseNe (const internal::string & str) inline
References MakePolymorphicMatcher().
StrEq()
PolymorphicMatcher< internal::StrEqualityMatcher< internal::string > > testing::StrEq (const internal::string & str) inline
References MakePolymorphicMatcher().
StrNe()
PolymorphicMatcher< internal::StrEqualityMatcher< internal::string > > testing::StrNe (const internal::string & str) inline
References MakePolymorphicMatcher().
Truly()
template<typename Predicate > PolymorphicMatcher< internal::TrulyMatcher< Predicate > > testing::Truly (Predicate pred) inline
References MakePolymorphicMatcher().
TypedEq()
template<typename Lhs , typename Rhs > Matcher< Lhs > testing::TypedEq (const Rhs & rhs) inline
References Eq().
UnorderedElementsAre() [1/11]
internal::UnorderedElementsAreMatcher< std::tr1::tuple<> > testing::UnorderedElementsAre () inline
References Args().
UnorderedElementsAre() [2/11]
template<typename T1 > internal::UnorderedElementsAreMatcher< std::tr1::tuple< typename internal::DecayArray< T1 >::type > > testing::UnorderedElementsAre (const T1 & e1) inline
References Args().
UnorderedElementsAre() [3/11]
template<typename T1 , typename T2 > internal::UnorderedElementsAreMatcher< std::tr1::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type > > testing::UnorderedElementsAre (const T1 & e1, const T2 & e2) inline
References Args().
UnorderedElementsAre() [4/11]
template<typename T1 , typename T2 , typename T3 > internal::UnorderedElementsAreMatcher< std::tr1::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type > > testing::UnorderedElementsAre (const T1 & e1, const T2 & e2, const T3 & e3) inline
References Args().
UnorderedElementsAre() [5/11]
template<typename T1 , typename T2 , typename T3 , typename T4 > internal::UnorderedElementsAreMatcher< std::tr1::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type > > testing::UnorderedElementsAre (const T1 & e1, const T2 & e2, const T3 & e3, const T4 & e4) inline
References Args().
UnorderedElementsAre() [6/11]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 > internal::UnorderedElementsAreMatcher< std::tr1::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type, typename internal::DecayArray< T5 >::type > > testing::UnorderedElementsAre (const T1 & e1, const T2 & e2, const T3 & e3, const T4 & e4, const T5 & e5) inline
References Args().
UnorderedElementsAre() [7/11]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 > internal::UnorderedElementsAreMatcher< std::tr1::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type, typename internal::DecayArray< T5 >::type, typename internal::DecayArray< T6 >::type > > testing::UnorderedElementsAre (const T1 & e1, const T2 & e2, const T3 & e3, const T4 & e4, const T5 & e5, const T6 & e6) inline
References Args().
UnorderedElementsAre() [8/11]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 > internal::UnorderedElementsAreMatcher< std::tr1::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type, typename internal::DecayArray< T5 >::type, typename internal::DecayArray< T6 >::type, typename internal::DecayArray< T7 >::type > > testing::UnorderedElementsAre (const T1 & e1, const T2 & e2, const T3 & e3, const T4 & e4, const T5 & e5, const T6 & e6, const T7 & e7) inline
References Args().
UnorderedElementsAre() [9/11]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 > internal::UnorderedElementsAreMatcher< std::tr1::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type, typename internal::DecayArray< T5 >::type, typename internal::DecayArray< T6 >::type, typename internal::DecayArray< T7 >::type, typename internal::DecayArray< T8 >::type > > testing::UnorderedElementsAre (const T1 & e1, const T2 & e2, const T3 & e3, const T4 & e4, const T5 & e5, const T6 & e6, const T7 & e7, const T8 & e8) inline
References Args().
UnorderedElementsAre() [10/11]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 > internal::UnorderedElementsAreMatcher< std::tr1::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type, typename internal::DecayArray< T5 >::type, typename internal::DecayArray< T6 >::type, typename internal::DecayArray< T7 >::type, typename internal::DecayArray< T8 >::type, typename internal::DecayArray< T9 >::type > > testing::UnorderedElementsAre (const T1 & e1, const T2 & e2, const T3 & e3, const T4 & e4, const T5 & e5, const T6 & e6, const T7 & e7, const T8 & e8, const T9 & e9) inline
References Args().
UnorderedElementsAre() [11/11]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 > internal::UnorderedElementsAreMatcher< std::tr1::tuple< typename internal::DecayArray< T1 >::type, typename internal::DecayArray< T2 >::type, typename internal::DecayArray< T3 >::type, typename internal::DecayArray< T4 >::type, typename internal::DecayArray< T5 >::type, typename internal::DecayArray< T6 >::type, typename internal::DecayArray< T7 >::type, typename internal::DecayArray< T8 >::type, typename internal::DecayArray< T9 >::type, typename internal::DecayArray< T10 >::type > > testing::UnorderedElementsAre (const T1 & e1, const T2 & e2, const T3 & e3, const T4 & e4, const T5 & e5, const T6 & e6, const T7 & e7, const T8 & e8, const T9 & e9, const T10 & e10) inline
References Args().
UnorderedElementsAreArray() [1/4]
template<typename T , typename A > internal::UnorderedElementsAreArrayMatcher< T > testing::UnorderedElementsAreArray (const ::std::vector< T, A > & vec) inline
References UnorderedElementsAreArray().
UnorderedElementsAreArray() [2/4]
template<typename T > internal::UnorderedElementsAreArrayMatcher< T > testing::UnorderedElementsAreArray (const T * pointer, size_t count) inline
References UnorderedElementsAreArray().
UnorderedElementsAreArray() [3/4]
template<typename T , size_t N> internal::UnorderedElementsAreArrayMatcher< T > testing::UnorderedElementsAreArray (const T(&) array[N]) inline
References UnorderedElementsAreArray().
UnorderedElementsAreArray() [4/4]
template<typename Iter > internal::UnorderedElementsAreArrayMatcher< typename ::std::iterator_traits< Iter >::value_type > testing::UnorderedElementsAreArray (Iter first, Iter last) inline
Referenced by UnorderedElementsAreArray(), UnorderedElementsAreArray(), and UnorderedElementsAreArray().
Value()
template<typename T , typename M > bool testing::Value (const T & value, M matcher) inline
References Matches().
Referenced by testing::internal::TuplePrefix< N >::ExplainMatchFailuresTo().
WhenSorted()
template<typename ContainerMatcher > internal::WhenSortedByMatcher< internal::LessComparator, ContainerMatcher > testing::WhenSorted (const ContainerMatcher & container_matcher) inline
WhenSortedBy()
template<typename Comparator , typename ContainerMatcher > internal::WhenSortedByMatcher< Comparator, ContainerMatcher > testing::WhenSortedBy (const Comparator & comparator, const ContainerMatcher & container_matcher) inline
WithArg()
template<int k, typename InnerAction > internal::WithArgsAction< InnerAction, k > testing::WithArg (const InnerAction & action) inline
WithArgs() [1/10]
template<int k1, typename InnerAction > internal::WithArgsAction< InnerAction, k1 > testing::WithArgs (const InnerAction & action) inline
WithArgs() [2/10]
template<int k1, int k2, typename InnerAction > internal::WithArgsAction< InnerAction, k1, k2 > testing::WithArgs (const InnerAction & action) inline
WithArgs() [3/10]
template<int k1, int k2, int k3, typename InnerAction > internal::WithArgsAction< InnerAction, k1, k2, k3 > testing::WithArgs (const InnerAction & action) inline
WithArgs() [4/10]
template<int k1, int k2, int k3, int k4, typename InnerAction > internal::WithArgsAction< InnerAction, k1, k2, k3, k4 > testing::WithArgs (const InnerAction & action) inline
WithArgs() [5/10]
template<int k1, int k2, int k3, int k4, int k5, typename InnerAction > internal::WithArgsAction< InnerAction, k1, k2, k3, k4, k5 > testing::WithArgs (const InnerAction & action) inline
WithArgs() [6/10]
template<int k1, int k2, int k3, int k4, int k5, int k6, typename InnerAction > internal::WithArgsAction< InnerAction, k1, k2, k3, k4, k5, k6 > testing::WithArgs (const InnerAction & action) inline
WithArgs() [7/10]
template<int k1, int k2, int k3, int k4, int k5, int k6, int k7, typename InnerAction > internal::WithArgsAction< InnerAction, k1, k2, k3, k4, k5, k6, k7 > testing::WithArgs (const InnerAction & action) inline
WithArgs() [8/10]
template<int k1, int k2, int k3, int k4, int k5, int k6, int k7, int k8, typename InnerAction > internal::WithArgsAction< InnerAction, k1, k2, k3, k4, k5, k6, k7, k8 > testing::WithArgs (const InnerAction & action) inline
WithArgs() [9/10]
template<int k1, int k2, int k3, int k4, int k5, int k6, int k7, int k8, int k9, typename InnerAction > internal::WithArgsAction< InnerAction, k1, k2, k3, k4, k5, k6, k7, k8, k9 > testing::WithArgs (const InnerAction & action) inline
WithArgs() [10/10]
template<int k1, int k2, int k3, int k4, int k5, int k6, int k7, int k8, int k9, int k10, typename InnerAction > internal::WithArgsAction< InnerAction, k1, k2, k3, k4, k5, k6, k7, k8, k9, k10 > testing::WithArgs (const InnerAction & action) inline
WithoutArgs()
template<typename InnerAction > internal::WithArgsAction< InnerAction > testing::WithoutArgs (const InnerAction & action) inline
Variable Documentation
_
const internal::AnythingMatcher testing::_ = {}
GTEST_ATTRIBUTE_UNUSED_
class GTEST_API_ testing::InSequence testing::GTEST_ATTRIBUTE_UNUSED_
kMaxStackTraceDepth
const int testing::kMaxStackTraceDepth = 100